# Introduction 

The world’s oceans cover approximately 70% of the planet’s surface and are home to a wide range of organisms and specialist habitats. The oceans and the biodiversity that they sustain also provide ecosystem services that are vital to the function of the Earth’s climate and to human welfare. There is a broad consensus within the scientific community that we know remarkably little about these environments but that we need to do more to conserve and understand these environments and to promote research that generates benefits for human welfare. This is particularly true for areas in the deep seas which fall outside the territorial boundaries of countries, known as Areas Beyond National Jurisdiction (ABNJ).

Member States of the United Nations are presently debating a potential implementing agreement (or agreements) on the conservation and sustainable use of marine biodiversity and access to genetic resources and benefit-sharing in Areas Beyond National Jurisdiction within the framework of the United Nations Convention on the Law of the Sea (UNCLOS). Areas Beyond National Jurisdiction are the parts of the oceans and seabed that fall outside the 200 nautical mile boundary of state Exclusive Economic Zones (hereafter, the EEZ). Areas Beyond National Jurisdiction (ABNJ) encompass approximately two thirds of the world’s oceans (the High Seas) and 60% of the seabed (known as the Area) [@Broggiato_2014]. In this report we simply call these areas the deep-sea. The deep-sea includes oceanic ridges such as the Mid-Atlantic Ridge, seamounts and knolls, deep-sea trenches and troughs, hydrothermal vents, cold seeps and mud volcanoes and vast abyssal plains stretching from ocean ridges to tectonic subduction zones at the continental margins where the jurisdictions of states begin. Governments are debating a range of potential options addressing topics such as protected areas and area based management tools, environmental impact assessments, capacity building, the transfer of marine technologies and access and benefit-sharing for marine genetic resources.

One of the challenges confronting governments is the significant gap in scientific knowledge and understanding of marine biodiversity in the deep-sea and of wider human uses of marine genetic resources. The recently completed _Census of Marine Life_ has greatly improved knowledge and understanding of marine biodiversity while at the same time emphasising how much more there is still to know [@2010_5234]. _Valuing the Deep_ sets out to advance knowledge and understanding of current research on marine genetic resources in the deep-sea and focuses on investigating human uses of marine genetic resources from the deep-sea and their actual and potential economic value. In particular, we set out to contribute to an understanding of the implications of potential measures on access to marine genetic resources and benefit-sharing under debate at the UN. To our knowledge, this is the first systematic effort to understand the uses and potential economic value of marine genetic resources from the deep-sea on a global scale. Given the scale of this task, much remains to be done to advance methodological development and improve the knowledge base to inform evidence-based decision-making. _Valuing the Deep_ is simply one more step in that process. 

Marine genetic resources can be broadly understood as the genetic components of organisms, biochemical compounds that are expressed through the interactions between these components, <!-- wording --> the organisms themselves, and the communities of which they form a part. Organisms form part of complex ecosystems characterised by a wide range of distinct and overlapping habitats. An organism’s role or position within these ecosystems may be confined to a specific niche or they can be generalists able to live in a variety of conditions. Life in the deep-sea extends from pore spaces in the oceanic crust and layers of sediment through to specialised habitats such as hydrothermal vents, cold seeps and cold water reefs to different levels in the water column (pelagic zones) from depths ranging up to 11,000 metres. 

Basic genetic material and expression products are transformed into a resource through the combination of the material itself and human knowledge of its properties and potential uses. Many serious challenges remain in the basic ability of scientists to observe, collect and culture organisms from the deep-sea. The majority of research in the deep-sea is directed towards advancing basic knowledge of these environments aided by new technological developments such as ocean floor observatories, Remote Operated Vehicles (ROVs), Autonomous Underwater Vehicles (AUVs) and manned submersibles supported by ships, specialists, teams of technicians and laboratories backed by scientific funding agencies from multiple countries. This research is expensive and underfunded relative to the enormity of deep-sea. However, the results of biological research are increasingly becoming available in informational form _(in silico)_ as specific DNA, RNA and amino acid sequences. These resources may ultimately find applications and form part of products across a range of economic sectors such as pharmaceuticals, cosmetics, foodstuffs and industrial enzymes that contribute to economic growth and job creation. 

Countries such as the UK and the wider European Union have placed considerable emphasis on the potential of advances in science and technology to promote long-term economic growth through biotechnology. This increasingly finds form in the concept of the bioeconomy and strategies to advance the creation of a bioeconomy [@2009_9675; @europeancommission]. The bioeconomy is directed to realising the benefits of advances in biotechnology in areas such as agriculture, health and industry and encompasses sectors such as pharmaceuticals and emerging areas of science and technology such as synthetic biology, systems biology, metabolic engineering and bionanotechnology. 

Marine genetic resources increasingly form part of future visions of the emerging bioeconomy and wider strategies focusing on the importance of marine and maritime resources to national and regional economies. In the European Union marine or blue biotechnology forms part of the _Blue Growth_ strategy that focuses on the marine and maritime dimensions of the _Europe 2020_ strategy [@europeancommission]. One of the main challenges in addressing the value of marine genetic resources is that economic value is commonly presented in terms of potential rather than actual value. The Marine Board of the European Science Foundation has also emphasised the importance of marine biotechnology and set out a strategy focusing on developments in relation to food, energy, health, environmental health, new enzymes and biomaterials. Thus, the Marine Board estimated that in 2010 the global market for marine biotechnology was €2.8 billion and displayed a cumulative annual growth rate of 4-5% [@Querellou_2010]. They argue that: “Less conservative estimates predict an annual growth in the sector of up to 10-12% in the coming years, revealing the huge potential and high expectations for further development of the Marine Biotechnology sector at a global scale” (@Querellou_2010: 9). 

Expectations regarding the potential economic value of marine genetic resources spill over into debates on marine genetic resources from Areas Beyond National Jurisdiction. In particular, a series of reports and academic articles focusing on Areas Beyond National Jurisdiction have emphasised the growth of scientific and commercial interest in marine genetic resources over the last decade [@Broggiato_2014; @fedder2013marine; @2005; @Leary_2009; @Arrieta_2010; @Arnaud_Haond_2011]. This extends to research on patent activity as an indicator of commercial research and development. Recent research identified 558 distinct named marine species in a set of patents containing DNA sequences suggesting strong interest in commercial research and development involving marine organisms [@Arnaud_Haond_2011]. 

However, while a growing body of literature indicates increasing research and commercial interest in marine genetic resources in general and in the deep-sea in particular, it is widely recognised that the knowledge base for decision-making involving deep-sea marine genetic resources is presently very limited. _Valuing the Deep_ aims to contribute to the evidence base to inform decision-making in five ways:

1. We conducted a large-scale empirical review of the scientific literature on the deep-sea, marine natural products and marine biotechnology to clarify the who, what and where of deep-sea research and commercial research and development; 

2. We text mined 14,038,743 patent documents for 402,540 marine species from the World Register of Marine Species (WoRMS) in order to identify the who, what and where of international patent activity involving marine species;

3. In order to distinguish between marine genetic resources from inside Exclusive Economic Zones and Areas Beyond National Jurisdiction we combined the patent data with available taxonomic information on the geographic distribution of species and depth data using the Global Biodiversity Information Facility (GBIF) and Ocean Biogeographic Information System (OBIS) to identify and map marine organisms appearing in patent data in the deep seas with corresponding depths in the water column;

4. We reviewed recent literature on marine natural products in relation to pharmaceuticals, cosmetics, enzymes, nutraceuticals and other technology sectors to identify products from deep-sea organisms;

5. With generous assistance from the International Network of Scientific Investigation of Deep-Sea Ecosystems (INDEEP) we carried out a three-month expert Delphi study to identify key issues and potential options on conservation, sustainable use and access and benefit-sharing from deep-sea marine genetic resources to inform wider debates on any implementing agreement under UNCLOS. 

_Valuing the Deep_ provides a detailed empirical analysis of the uses of marine genetic resources, their economic value (where known) and their potential value including detailed information on the main actors engaged in the utilisation of marine genetic resources across a range of economic sectors. In particular, we provide a global overview of available data on economic activity and consider the relevance of this activity to the UK economy and scientific community. 

Our main focus is the implications of potential measures on access to genetic resources and benefit-sharing in ABNJ. We find support for the argument that there is growing scientific interest in the deep-sea and establish that the UK research community forms a very important part of wider international networks of researchers from 150 countries focusing on marine organisms from the deep-sea. 

However, our research also strongly suggests that research is concentrated in a small number of locations relative to the geographic scale of the deep-sea. This reflects the formidable financial and logistical costs and challenges involved in conducting research in the deep-sea. We conclude that the introduction of regulations on access to marine genetic resources in the deep-sea for research purposes would impose undue and unnecessary burdens on the research community at the expense of enhancing knowledge and understanding of these environments. We propose that voluntary codes of conduct and guidelines provide the most sensible way forward for ensuring that research on marine genetic resources does not result in negative environmental impacts and that members of the deep-sea research community will be best placed to advise on existing codes of conduct and potential future needs [@Broggiato_2014]. However, we also argue that improvements are desirable in understanding where deep-sea research is taking place and that this need could perhaps be met through a simple system of notification that research has taken place [@Broggiato_2014; @Leary_2012; @Tvedt_2013; @Druel_2014]. Any such notification system should not include restrictions on access. 

With respect to potential options on benefit-sharing, we argue that improved communication and coordination between the networks of funding agencies involved in supporting deep-sea research could contribute to reducing duplication of effort and form the basis of a strategic approach to improving research coverage for the deep-seas to advance human knowledge and understanding. Building on the results of the Delphi study we recommend that the deep-sea research community and research networks should directly participate in decision-making on research priorities and development of wider strategies or a road map for improving knowledge and understanding of the deep-sea. We further argue that expanding knowledge and understanding of the deep-sea requires additional incentives to encourage researchers to move outside existing areas of concentration to higher risk research areas such as the middle of the water column, the abyssal plain or oceanic crust. The existing literature on debates at the UN focuses on potentially using the multi-lateral benefit-sharing fund under the International Treaty on Plant Genetic Resources for Food and Agriculture as a model for benefit-sharing for the deep-sea [@Broggiato_2014; @Leary_2012; @Tvedt_2013; @Druel_2014]. We propose that a venture fund to promote exploratory research on marine genetic resources outside existing areas of research concentration coupled with the promotion of international collaboration could contribute to improving the knowledge base for the wider benefit of the international community. To reduce overheads and transaction costs such a venture fund could be administered through coordination between existing funding agencies rather than the creation of a new institution or transfer of authority to an existing institution. 

Our review of the patent data from the main patent jurisdictions (the European Patent Office, the United States Patent and Trademark Office, and the Patent Cooperation Treaty) between 1976 and October 2013 identified references to 4,759 marine species in patent documents. The majority of species were identified as being distributed inside the Exclusive Economic Zone (2,959 species) with 1,800 being distributed in the deep-sea. With very few exceptions species identified in the deep-sea are also distributed inside the EEZ. Available depth data suggests that deep-sea species are predominantly located in the epipelagic zone (0–200 metres) with 1,461 species located in the epipelagic zone and 339 from the deep-sea zone (below 200 metres) in the water column. However, the ability to map species by depth in the deep-sea is seriously affected by a lack of depth data for bacteria and archaea in taxonomic databases. 

With respect to patent trends for documents that make reference to marine organisms as a whole, first filings of new inventions rose steadily to a peak of 1,703 filings in 2008 but are relatively stable at +/- 1,500 filings per year. However, there is increasing demand for protection in multiple countries signifying that applicants believe that the cost of patent protection in multiple markets will ultimately be beneficial for their products. UK international patent activity in the period 1976-2013 made reference to a total of 708 marine species with 241 species appearing in the titles, abstracts or claims. Unilever, Syngenta (UK), AstraZeneca, the Medical Research Council, Astex Therapeutics, the University of London and Oxford University led patent activity. 

For global patent activity outside the EEZ we divided the data into two zones, the epipelagic zone (0-200 m in depth) and deep-sea zone (below 200 m in depth). Because of limitations in the availability of depth data for bacteria and archaea, the data is not presently sufficiently robust to draw clear conclusions on trends by depth in the water column. In total, we identified 8,039 first filings of patent applications referencing species known to occur in Areas Beyond National Jurisdiction with activity peaking in 2008 at 629 filings before declining between 2009 and 2010. Patent trends for deep-sea species appearing in the titles, abstract or claims of patent filings provide an indicator of patent applications that are in some important sense 'about' these species. Trends in this area displayed a much lower filing rate with 1,358 filings peaking at 93 filings in 2008. In practice, patent filing trends for species will rest somewhere between the total number of documents referencing a marine species occurring outside the EEZ and documents referencing a species in the title, abstract or claims. Further methodological refinement is therefore desirable in future work. 

While interest in marine species as a whole is increasing, our data suggests that this interest mainly focuses on species from inside the EEZ. In our view, and taking into account the difficulties of separating organisms by geo-political boundaries, patent activity involving deep-sea species as a whole is more limited than might be assumed in debates in the context of UNCLOS. These findings are consistent with statements from expert participants in the Delphi study that deeper does not necessarily mean more novelty and that considerable biodiversity exists in coastal areas. Furthermore, these findings are consistent with the general observation that it is difficult and expensive to access, collect and culture organisms from the deep-sea.   

A third aspect of our research focused on reviewing the recent literature on products based on marine genetic resources. In particular, the natural products literature has emphasised growing interest in marine derived compounds. For example, an authoritative review of marine natural compounds for 2011 found a total of 1,152 new compounds described in 352 articles representing a 15% increase over 2010 when the corresponding figure was 1,003 new compounds [@Blunt_2012; @Blunt_2013]. Between 2009 and 2011 an estimated 262 marine compounds formed part of the pre-clinical pharmaceutical pipeline [@Mayer_2013]. However, research interest does not directly equate with successful product development. Thus, between 2004 and 2013, 28 marine natural products were in clinical trials but 18 of the trials were discontinued [@Martins_2014]. A total of 7 marine based pharmaceuticals are presently on the market (with an additional approved pharmaceutical having been withdrawn) [@Martins_2014]. 

Our research also reviewed available data on industrial enzymes where we were able to identify at least six marketed enzymes from marine organisms, including well known proteins such as Green Fluorescent Protein. Of these four are from the deep-sea, one lacks a species name, while Squalene from shark liver oil lacks information on the specific shark species. Based on the literature at least four cosmeceuticals (cosmetics with medical benefits) on the market are based on marine natural products. Of these two species were drawn from the deep-sea, one from inter-tidal Antarctic waters and one deep-sea organism from within the EEZ of Portugal. Additional products, such as fish oils and krill oils are also available on the market. Growing interest is also reported in the scientific literature in marine microorganisms as sources of nutraceuticals and functional foods [@Dewapriya_2014]. However, the data is limited to potential products and development is likely to be affected by safety standards for microbial strains for foods for human consumption. Expert participants in the Delphi study expressed significant concerns about the environmental impacts of consumptive use of marine organisms for the nutraceuticals market. 

In considering this data it becomes clear that debates on marine genetic resources in general, and deep-sea marine genetic resources in particular, are primarily directed towards the realisation of potential economic value rather than actual economic value. In the case of the pharmaceuticals sector it appears reasonable to assume that increased interest in marine natural compounds will translate into more compounds entering the pharmaceutical pipeline. However, this does not inevitably mean that more marine based products will win approval relative to other sources of compounds. The available data suggests these compounds will mainly come from organisms inside the EEZ and thus fall within the scope of the Convention on Biological Diversity and the 2010 Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization. 

In considering the data presented in this report and its implications for the UK economy in the context of debates on any implementing agreement within the framework of UNCLOS, it will be important to maintain the distinction between the actual economic value of marine genetic resources from the deep-sea and the potential economic value of these resources. In particular, the conflation of potential value with actual value could lead to unfounded expectations around “blue gold” and demands for strong regulation of both access to genetic resources and benefit-sharing for marine genetic resources from the deep-sea. This will mimic earlier debates on “green gold” and “biopiracy” under the Convention on Biological Diversity. The regulation of access to marine genetic resources for research, as opposed to harvesting for consumption, could stifle what is already an extremely challenging area of research. Furthermore, in connection with benefit-sharing, the evidence available to us does not suggest that research on marine genetic resources from Areas Beyond National Jurisdiction (ABNJ) generates significant income for researchers, companies or countries from the sale of commercial or other products. In fact, deep-sea research mainly generates costs. 

This suggests a need to think carefully about benefit-sharing. The existing literature highlights options such as a global multilateral benefit-sharing fund drawing on similarities with the multilateral system established under the International Treaty on Plant Genetic Resources for Food and Agriculture [@Broggiato_2014; @Leary_2012; @Tvedt_2013; @Druel_2014]. A second option includes creating a common pool of sampled marine genetic resources that draws on an open source approach in which access to samples and data is central [@Tvedt_2013]. Other options include regional approaches that focus on the role of regional bodies and programmes such as the Regional Seas Programme supported by UNEP and involving 140 States that could potentially address access and benefit-sharing issues in ABNJ [@Rochette_2014]. The present research has identified a range of other issues that need to be considered in debates about benefit-sharing. 

As is increasingly recognised, international research in the deep-sea involves international collaborations in sharing and coordinating access to ship time, research equipment including submersibles, ROVs (Remote Operated Vehicles), AUVs (Autonomous Underwater Vehicles), sea floor observatories and specialist laboratories. International cooperation in deep-sea research constitutes a network through which both monetary and non-monetary benefits flow. In our view, the starting point for debates on benefit-sharing should be the existing practices of researchers and funding agencies with a view to strengthening international cooperation, capacity building and monetary and non-monetary benefit-sharing for deep-sea marine research. We adopt the view that:

1. The aim of any benefit-sharing measures for marine genetic resources should be to promote and extend deep-sea research in Areas Beyond National Jurisdiction to advance human knowledge and understanding of the deep-sea; 

2. The approach to addressing 1. should be to build upon and strengthen existing practices within the deep-sea research community and enhance synergies in international research funding through the promotion of communication and coordination between funding agencies, such as a joint road map;

3. The promotion of exploratory research is central to enhancing human knowledge and understanding of the deep-sea. However, additional incentives in the form of a cooperative venture fund are likely to be needed to support risky exploratory research beyond existing areas of research concentration;

4. The pursuit of commercial innovation should not be a pre-condition of venture funding in order to promote basic research. However, a portion of any financial benefits from commercial products or intellectual property assets arising from venture funding should be reinvested in the venture fund to promote the longer-term sustainability of the venture fund for deep-sea research. 

The approach outlined above shares similarities with existing proposals. However, it differs in emphasis and orientation. In this view the only legitimate purpose for introducing benefit-sharing measures for marine genetic resources is to promote and extend research in the deep-sea for the wider long-term benefit of humanity. The types of benefit-sharing that are required to advance this aim should be based upon the practices and priorities identified by members of the deep-sea research community themselves and involve existing research networks such as INDEEP. The promotion of communication and coordination between funding agencies should build on existing experiences (e.g. bilateral and multilateral research programmes) and, with the participation of the deep-sea research community, establish a framework road map for deep-sea research in ABNJ. The proposed venture fund for exploratory research could be administered through existing funding agencies as a distributed pool of funds and would not require a new administrative institution or transfer of authority to an existing institution. Countries participating in the venture fund would agree that international collaboration, including developing country participation, would be an eligibility requirement to access the fund. 

In considering these options, the most common point of reference in existing debates is the multi-lateral benefit-sharing fund established under the Plant Treaty. One of the most important lessons learned from the Plant Treaty is that governments will be the primary contributors to these types of funds in the short to medium term [@moeller2013identifying]. In our view, given the lack of products on the market, it is highly likely that this experience would be repeated for a benefit-sharing mechanism forming part of any implementing agreement. It is therefore prudent to anticipate that governments would be the primary contributors to such a fund. For this reason, we propose focusing on enhancing communication and coordination between existing funding agencies. Furthermore, given the lack of funding for deep-sea marine research, in our view it is reasonable to argue that countries seeking to access any venture fund should be required to contribute to the venture fund as a condition of participation by their researchers. Recognising the varying abilities of countries to contribute funding, these contributions could be tiered. Contributions to the venture fund from private sources should be encouraged, including companies working on technology development for deep-sea exploration, but should not be allowed to determine the strategic purpose of the venture fund. 

The remainder of this report is divided into seven chapters. Chapter 2 provides an overview of deep-sea habitats and up-to-date information on the status of scientific knowledge about deep-sea habitats and threats to these habitats. This chapter assumes no prior knowledge of the deep-sea and is intended to provide an up-to-date introductory guide based on the latest scientific research. Chapter 3 examines the ‘who, what and where’ of deep-sea marine scientific research and research on marine natural products and biotechnology. Using scientometric approaches the chapter identifies key actors, research themes, funding agencies and geographical places that are the focus of research activity. Chapter 4 examines international and UK patent activity involving marine genetic resources from the deep-sea. Chapter 5 explores available information about the origins of the organisms and genetic material appearing in patent documents. Chapter 6 reviews available information about marine natural products that are on the market, building on existing research and reports. Chapter 7 presents the results of the expert Delphi study. <!-- Annex 1 provides details of the search strategy for the scientific literature. Annex 2 provides details of patent documents containing references to deep-sea marine species. Annexes not included in bookdown book -->