# Executive Summary

The following represent the key findings of the Valuing the Deep project on economic activity relating to marine genetic resources from Areas Beyond National Jurisdiction (the deep-sea) and their relevance to debates on access to genetic resources and benefit-sharing within the framework of the United Nations Convention on the Law of the Sea (UNCLOS). 
The Valuing the Deep project consisted of four main components:

1. Quantitative analysis and mapping of the scientific literature on the deep-sea;
2. Quantitative analysis of patent data on marine genetic resources from the deep-sea;
3. An expert Delphi study consultation to examine scientific and stakeholder perspectives on an implementing agreement (or agreements) on the conservation and sustainable use of marine biodiversity and access and benefit-sharing in Areas Beyond National Jurisdiction (ABNJ);
4. A review of the literature on the actual and potential market value of marine genetic resources with a focus on marketed products.
The main objective of the project was to inform UK and wider European and international policy debates on the need for an implementing agreement (or agreements) on the conservation and sustainable use of marine biodiversity in Areas Beyond National Jurisdiction under UNCLOS and, specifically, the possible inclusion of an access and benefit-sharing mechanism for marine genetic resources. The results of the research are also relevant to the programme of work on marine biodiversity under the United Nations Convention on Biological Diversity, regional agreements and the work of the World Intellectual Property Organisation. 

## Main Findings

The main finding of the report is that there is growing interest in marine genetic resources including from deep-water locations. However, the majority of scientific research and commercial research and development, including deep-water locations, focuses on marine organisms from habitats inside national jurisdictions demarcated by Exclusive Economic Zones (hereafter, the EEZ). The available evidence suggests that marine scientific research in Areas Beyond National Jurisdiction concentrates around a limited number of sites relative to the scale of the deep-sea. 

Analysis of patent data reveals growing references to deep-sea marine organisms but that these organisms also occur inside the EEZ and in terrestrial aquatic environments. This makes it difficult to determine with precision whether a sample originated from Areas Beyond National Jurisdiction or within national jurisdictions. Geographical mapping of references to species from Areas Beyond National Jurisdiction produced limited results focusing on the East Pacific Rise and Mid-Atlantic Ridge. In the majority of cases it appears likely that applicants referencing deep-sea locations obtained genetic material or data from commercial sources, public collections or databases rather than field collections.

Analysis of the scientific literature on trends in marine natural compounds revealed a growing interest in marine natural compounds that is primarily concentrated in marine invertebrates distributed inside national jurisdictions. However, a focus on invertebrates as a source of compounds is giving way to growing interest in microorganisms that live in a symbiotic relationship with these organisms. Deep-sea organisms from Areas Beyond National Jurisdiction can be classified as an emerging area of interest in marine natural products research in the context of the dominant existing focus on invertebrates.  

A review of the recent literature on marketed products from marine organisms revealed that the majority of products derive from organisms from inside national jurisdictions with limited exceptions for enzymes from extremophiles and Antarctic krill as a source of nutraceutical products. As such, growing interest in marine genetic resources as a source of products does not necessarily correlate with increasing interest in marine organisms from the deep-sea. This reflects the considerable costs and logistical difficulties involved in accessing genetic material from the deep-sea, particularly below 200 metres, relative to other potential sources and the difficulties of keeping deep-sea organisms alive for further research. We therefore conclude that debates on the economic value of marine genetic resources are focused on potential economic value rather than actual economic value. 

The Valuing the Deep Delphi study provided a rich source of information from deep-sea marine scientific researchers and stakeholders. Expert views confirm that the majority of existing research and commercial interest in marine genetic resources occurs inside national jurisdictions and support the view that biological prospecting outside national jurisdictions is presently limited. Experts suggest that where industry does become involved this takes place following initial discovery and analysis by publicly funded researchers. Experts narrowly agreed that there is increasing interest in deep-sea organisms from industry but that this does not necessarily translate into investment. While recognising the variety of views expressed by experts we therefore conclude that commercial interest in deep-sea marine genetic resources is emergent but limited.   

Experts generally agreed that policy-makers believe that there is increasing commercial interest in marine genetic resources arising from a combination of a perception of the “blue gold of marine biotech”, a “fear of missing out” and a desire for their own scientists to participate in the emerging field of deep-sea research on an equal footing with other countries. National and regional blue growth strategies, notably from the European Union, were identified as key drivers towards commercial exploitation with more general academic pressures towards demonstrating commercially useful results also being noted by experts.

Experts generally agreed that the environmental impacts of both marine genetic research in the deep-sea and bioprospecting were likely to be limited while emphasising the need for caution in fragile habitats. Experts held the view that the environmental impacts of research on marine genetic resources and bioprospecting pale into insignificance compared with commercial fishing and mining and described this as the equivalent of “comparing apples and oranges”. There was a strongly held view among participants that action was needed within the framework of UNCLOS to address the conservation and sustainable use of biodiversity in Areas Beyond National Jurisdiction. This extended to a need to address access and benefit-sharing for genetic resources under any implementing agreement (see below). 

In considering these findings we therefore conclude that current interest in marine genetic resources from Areas Beyond National Jurisdiction is emergent. It therefore follows that the negotiation of any implementing agreement within the legal framework of UNCLOS will focus on the potential economic value of marine genetic resources from the deep-sea. Clarity on this issue will facilitate discussion on the purpose of any implementing agreement on access and benefit-sharing and the appropriate means through which this purpose can be realised. In our view, the long term strategic purpose of such an agreement should be to promote investment in deep-sea research directed to advancing human knowledge and understanding of the deep-sea for the wider long term benefit of humanity. 

We now turn to potential elements of any implementing agreement involving access and benefit-sharing taking into account the results of the Valuing the Deep Delphi Study. 

##Habitats and Environmental Impacts
•	Expert participants in the Delphi study expressed the general view that the environmental impacts of deep-sea research on marine genetic resources are likely to be limited. However, they also emphasised a need for caution and noted the role of codes of conduct, such as the InterRidge, OSPAR Commission and Mediterranean Science Commission (CIESM) codes, in connection with issues such as re-sampling. This suggests that existing codes of conduct and guidelines for research on marine genetic resources and in marine habitats could be reviewed and incorporated within any implementing agreement;  
•	With respect to the wider environmental impacts of human interventions, such as commercial fishing or mining, some experts expressed concern that important habitats, notably cold-water coral reefs, are ignored in existing debates despite their key role as fisheries nurseries. This suggests that any measures proposed under any implementing agreement relating to environmental impacts should take account of the full range of habitats in Areas Beyond National Jurisdiction. 

Access to Marine Genetic Resources
•	It is widely recognised that research in deep-sea environments outside national jurisdiction is difficult, expensive, and there is not enough of it. Research on marine genetic resources, as opposed to commercial harvesting, has limited known environmental impacts and we find limited evidence of economically important commercial products that are on the market and originate from deep-sea environments in ABNJ; 
•	For this reason we do not advocate strong regulation of access to marine genetic resources in Areas Beyond National Jurisdiction. The Delphi study suggests that any access measures should recognise and build upon existing reporting practices within the deep-sea research community and that responsibility for initial reporting could be allocated to research cruise leaders; 
•	Information on research taking place in ABNJ could be improved through a simple system of notification that research is taking place [1]. However, care would be needed in the negotiation process to ensure that such a notification system does not become a vehicle for restricting access for marine scientific research.
Benefit-Sharing:
•	Based on the outcomes of the Delphi study it is our view that benefit-sharing measures should be built from the bottom up based on existing research practices in the deep-sea research community and directed to the purpose of promoting deep-sea research. In particular, experts highlighted issues such as enhanced coordination of cruises, participation from developing countries, collaboration in sample collection and data access as areas for benefit-sharing with a significant emphasis on non-monetary benefit-sharing.
•	Potential options for benefit-sharing could include:
•	Creating a centralised repository of exploration needs and gaps;
•	Promoting increased access to raw and published data from research by creating a common Clearing House Mechanism style interface for dispersed deep-sea research data while taking into account existing initiatives such as the Ocean Biogeographic Information System (OBIS) and the Global Biodiversity Information Facility; 
•	Consulting with the deep-sea research community to identify measures that might facilitate greater international cooperation and coordination in the planning and execution of research on the deep-sea taking into account needs for access to ship time, specialist vehicles, laboratories, technicians and data; 
•	Promoting greater communication and coordination between funding agencies supporting deep-sea research to reduce duplication of effort and enhance synergies. A common inter-agency framework road map directed to enhancing coverage of deep-sea research could facilitate coordination with limited transaction costs;
•	Considering a venture or exploration fund to promote research to advance knowledge and understanding of the deep-sea beyond existing areas of research concentration – such as the middle of the water column, seamounts, the oceanic crust etc. – in consultation with the deep-sea research community. Elements for developing a venture fund could include:
•	A fund that consists of a pool of funds linked to a common road map and administered by existing funding agencies. A venture fund consisting of a pool of funds linked to an agreed road map would not require a new institution and would limit transaction and administrative costs; 
•	An agreed road map based on consultation on priorities for research and cooperation with the deep-sea research community (see above);
•	A requirement for countries that wish their researchers to participate in the venture fund to contribute financial resources to the venture fund as a condition of access, while taking into account the varying economic circumstances of countries that may wish to participate; 
•	A requirement for international collaboration as a condition for applications to the venture fund including participation of researchers from developing countries that contribute to the venture fund;
•	Access to the venture fund would not discriminate by the type of marine genetic research (non-commercial or commercial). However, applicants to the venture fund would be required to return a portion of income from any commercial products or intellectual property assets arising from research to the venture fund as a contribution to the longer term sustainability of the fund. 
•	The proposals on benefit-sharing outlined above share some common features with existing proposals, such as promoting access to data. However they also differ in significant respects:
•	In our view the main and indeed only focus of any type of benefit-sharing measures should be the promotion of research on the deep-sea to enhance knowledge and understanding of the deep-sea for the wider long term benefit of humanity;
•	Any proposals on access or benefit-sharing measures should be developed in direct consultation with members of the deep-sea research community and build on, enhance and strengthen existing practices and international collaboration;
•	The promotion of a pool of funds linked to a common road map involving existing funding agencies could draw on existing experience and not involve creating new institutions. We would note that Delphi study participants were very sceptical about the potential role of institutions such as the International Seabed Authority. Some participants in the Delphi study mentioned the Global Ocean Commission as a credible and transparent institution with respect to a possible institutional mechanism on benefit-sharing;
•	The Multi-lateral Benefit-sharing Mechanism established under the International Treaty on Plant Genetic Resources for Food and Agriculture (the Plant Treaty) has been presented as a potential model for marine genetic resources from the deep-sea. This model clearly merits further discussion. However, experience demonstrates that in the early years, and for the foreseeable future, such benefit-sharing funds will depend on financial contributions from governments because of the long lead in times for the development of commercial products [2]. This suggests a need for governments to recognise that in the initial years, and possibly for the foreseeable future, in reality any benefit-sharing mechanism would depend on financial investments by states. 
•	Benefit-sharing and intellectual property rights. There was general agreement among Delphi study participants that there should be equitable sharing of the benefits arising from marine genetic resources. Experts also generally agreed that a requirement for benefit-sharing from commercial users would not impose undue burdens on innovation and that clarity on benefit-sharing could contribute to the creation of certainty and a level playing field for industry.
•	A range of views were expressed on intellectual property rights with a prevailing view that the pursuit of intellectual property should clearly be permitted while raising recognition of issues of access to data and the potential obstruction of scientific progress. 
•	The need to improve the quality of information on marine genetic resources in patent data was highlighted by Delphi study participants with a general view to improving the availability of information. Based on a review of patent data we propose that in the first instance patent applicants could be encouraged to provide more information in patent applications on the origins of marine genetic resources, where known, on a voluntary basis, and without prejudice to the processing of applications. This measure would improve knowledge and understanding of the role of marine genetic resources in innovation as a contribution to evidence based decision making over time. 
Capacity Building and Technology Transfer
Within the Valuing the Deep Delphi study the discussion of capacity building merged with discussion of technology transfer and technology needs. This perhaps reflects the fundamental dependence of research in the deep-sea on ships, specialist laboratories, and the equipment necessary to operate at depth. 
•	There is general agreement among experts on the need for more infrastructure and access to financial resources to enable training and research exchanges between developed and developing countries.
•	There is also general agreement on the need for improved coordination of research cruises to provide and share knowledge and training similar to the capacity building measures under the Convention on Biological Diversity and its Nagoya Protocol.
•	Other proposals include:
•	Coordination of research cruises so that adequate coverage is provided of biodiversity in Areas Beyond National Jurisdiction (see above);
•	A centralised repository of exploration needs and gaps (see above); 
•	A recognition that deep-sea research requires national level facilities and that this should be the main focus for targeted action through the development of national research programmes.
In connection with specific technologies:
•	An emphasis on unmanned autonomous tethered and untethered vehicles as the future of sampling (rather than simply more ships);
•	A continuing need for Remote Operated Vehicles and Human Operated Vehicles;
•	A need to develop in situ observatories with a suite of biological and genomic sensors to overcome limitations of access to the deep-sea;
•	The development of cheaper and faster sampling devices;
•	A need to develop pressure resistant and corrosion resistant materials for research at hydrothermal vents and the oceanic crust;
•	Enhanced telecoms capabilities to enable ship to shore communications with research teams.
Above all, in considering capacity building and technology related issues, an emphasis emerged on the need for an “agreed long-term strategy for this area” rather than “chasing money from government every few years in fire-fighting fashion”. 
Monitoring and Indicators
In connection with monitoring and indicators, expert participants in the Delphi study expressed a range of views including the view that this could be extremely difficult due to the scale of the deep-sea. However, a number of concrete proposals emerged that build on existing practices and extend to new technologies. These include:
•	Placing trust in cruise leaders to report findings accurately as a low impact cost effective monitoring system;
•	The use of self reporting by scientists and companies as part of Environmental Impact Assessment applications, sample collection reporting and benefit-sharing mechanisms as an indirect means of gaining an overview of activity;
•	Improvements in the disclosure of origin or source of material in patent applications.
Anticipatory Governance
In considering the outcomes of the quantitative and qualitative components of the Valuing the Deep study we conclude that the development of any implementing agreement with respect to access and benefit-sharing would be anticipatory in nature in so far that it addresses the potential economic value of marine genetic resources from Areas Beyond National Jurisdiction. We therefore propose that lessons be drawn from the emerging literature on the concept of anticipatory governance in the fields of climate change adaptation and new and emerging technologies that focus on foresight, the development of flexible adaptation strategies, monitoring and action in the development of any implementing agreement on access and benefit-sharing [3-6]. This approach would allow for a flexible and incremental approach to the governance of marine genetic resources in Areas Beyond National Jurisdiction that would promote marine scientific research and facilitate the realisation of the potential economic value of marine genetic resources from the deep-sea. 
References
1 Broggiato A, Arnaud-Haond S, Chiarolla C, Greiber T (2014) Fair and equitable sharing of benefits from the utilization of marine genetic resources in areas beyond national jurisdiction: Bridging the gaps between science and policy. Marine Policy. http://dx.doi.org/10.1016/j.marpol.2014.02.012.
2 Moeller N, Stannard C (2013) Identifying Benefit Flows: Studies on the Potential Monetary and Nonmonetary Benefits Arising from the International Treaty on Plant Genetic Resources for Food and Agriculture. Rome: International Treaty on Plant Genetic Resources for Food and Agriculture of the Food and Agriculture Organization.
3 Guston DH (2014) Understanding 'anticipatory governance'. Social Studies Of Science 44: 218-242.
4 Fuerth LS, Faber EMH (2013) Anticipatory Governance: Winning the Future. Futurist 47: 42-4+.
5 Fuerth LS (2009) Foresight and anticipatory governance. Foresight 11: 14-32.
6 Quay R (2010) Anticipatory Governance. Journal of the American Planning Association 76: 496-511.
