# The Value of Marine Genetic Resources

### Introduction

In this chapter we examine existing information on the actual and potential economic value of marine genetic resources drawing on the available scientific and market literature. As a starting point, we would emphasise that the value of marine organisms and habitats cannot simply be reduced to economic values. Rather our purpose is to assess existing information on the economic value of marine genetic resources from Areas Beyond National Jurisdiction as a contribution to evidence based analysis and debate on the economic value of these resources. Specifically, we argue that at present marine genetic resources fall into the domain of potential economic value rather than realised value. This has important implications for the design of a possible implementing agreement (or agreements) involving access and benefit-sharing within the framework of UNCLOS.

As a starting point important qualifications need to be made between the types of resources from marine organisms and between potential and actual values. With respect to the types of resources from marine organisms, we use the term marine genetic resources to mean genetic material from marine organisms falling into three broad categories:

1.	DNA, RNA and amino acid sequences and metabolic pathways performing particular functions or expressing products of interest; 
2.	Chemical compounds which may be characterised (where the structure of the compound is fully described) or uncharacterised;
3.	Raw extracts of marine organisms (i.e. fish oils). 

Resources falling into the first category are most commonly associated with the term genetic resources and would include industrial enzymes and research tools and are expressed in informational form as sequence data. Resources in the second category are most closely associated with pharmaceuticals and medicines where the identification and use of a characterised or uncharacterised compound does not depend on the analysis of the underlying genetic structure and interactions within an organism. The third category of raw extracts from marine organisms is most closely associated with the commercial harvesting of marine organisms, such as Antarctic krill to produce Omega-3 fatty acid based products or the use of extracts in cosmetics and nutraceuticals. These broad distinctions are useful for descriptive purposes in approaching the economic value of marine genetic resources. 

The first category of marine genetic resources typically focuses on a DNA and amino acid sequences used to encode information for the expression product of interest, such as an enzyme, that can then be synthesised in an industrial host organism such as a yeast or bacterium. Typically, this does not require large scale and repeated consumptive use of a marine organism once the synthesis process has been developed. For example, Green Fluorescent Protein (GFP) is widely used in biotechnology as an expression marker and is widely available as a synthesised commercial product for in the region of $250-300 per 300 micrograms (ug). The gene responsible for GFP was first isolated in the jellyfish Aequorea victoria but the protein is now produced in the engineered bacterium Escherichia coli. 

In contrast, the second category may require repeated collections of the organism of interest (such as a sea sponge) until such time that a compound is fully characterised and a synthetic or semi-synthetic route is found to produce the compound of interest. This can raise conservation issues such as in the case of the best selling cancer drug Taxol, derived from the endangered Pacific Yew (Taxus brevifolia), which required government incentives to promote the quest for a semi-synthetic and fully synthetic means to produce the compound that did not require repeated collection of the bark of this tree.  In the case of Taxol it took over 20 years before the first complete synthesis of the compound was reported. This type of issue is particularly prevalent for organisms such as sea sponges and tunicates that produce highly complex compounds in low quantities. 
The third category, raw extracts, usually depends upon repeated harvesting of an organism. In the case of marine genetic resources the best-known example is Omega-3 fatty acids that are extracted from fish, and more recently from Antarctic krill (Euphausia superba), to serve growing markets for Omega-3 products. Resources in categories 2 and 3 raise significant conservation issues, including in cases of apparently abundant resources such as krill.

It is important to recognise that different industry sectors make use of marine organisms as resources in a variety of ways with different consequences for conservation and sustainable use. Genetic resources used as informational resources in biotechnology based on small samples expressible as DNA, RNA and amino acid sequences do not have the same level of environmental impacts on source organisms as other uses of marine resources such as the collection of organisms using benthic trawls. Expert participants in the Valuing the Deep Delphi study noted a need for care in sampling activity but agreed that the environmental impacts of research sampling pale into insignificance compared with commercial fishing and mining. 

The second major qualification relates to the distinction between the potential and actual commercial value of marine genetic resources. This distinction is important in debates on access and benefit-sharing because a failure to distinguish between actual and potential value can lead to misrepresentation of the economic value of genetic resources. This in turn can distort debates on policy options by presenting potential value as actual value. These values can be considered in three categories: 

1.	Marine genetic resources that are of actual value for research in advancing knowledge and understanding of marine biodiversity but do not possess a realised, or realisable, commercial value.
2.	Marine genetic resources that are a focus of research and development directed to the potential development of new and useful products but have not yet resulted in commercial products that have passed through the regulatory approvals process and reached the market.
3.	Marine genetic resources or products that are on the market. 

The first two categories are associated with the potential economic value of marine genetic resources. Scientific literature and patent applications and grants typically fall into these categories: the former because they may suggest or directly point to potential commercial applications and the latter because patent applications are a public indicator of commercially oriented research and development that applicants believe has the potential to create a marketable application or product. 

Existing reports on the value of marine genetic resources frequently refer to compounds in clinical trials as an indicator of economic value. In practice, compounds in clinical trials normally fail to become actual marketed products (see below). This may be because the promising compound of interest lacks efficacy or displays insurmountable toxicity in animals or humans. As such, while displaying clear intent to create a commercial product, clinical trials are an indicator of potential rather than actual value. As this makes clear, the only true indicators of economic value are gleaned from products that reach the market. 

As we will see below, one of the reasons that existing analysis depends on indicators such as scientific publications, patents and clinical trials is the difficulty of identifying marketed products that originate from marine organisms. This in part reflects the considerable difficulties involved in tracing the origins of a marketed product back from a brand name to a compound, extract or sequence and the original organism. This problem cannot easily be overcome in the absence of a major research effort. A second aspect of this problem is the dispersed nature of data on products from marine organisms and a tendency for market related data to be locked up in commercial silos with significant barriers to entry. Finally, commercial sources of data do not typically display the methodological transparency required for scientific research. That is, the empirical foundations of calculations of actual or potential market valuations cannot be assessed. For this reason we have low confidence in market valuations from market research companies as a basis for informing international policy debates (see below). Nevertheless, in the absence of verifiable peer reviewed information we are obliged to use such information but invite the reader to take a sceptical position when considering market value estimates.

In considering the distinction between potential and actual value our purpose is not to neglect the importance of the pursuit of potential value in decision-making on marine genetic resources, rather, it is to promote clarity on the foundation for decision-making and whether it is based on existing evidence of economic value or on expectations and visions of potential economic value. For example, in 2010 the Marine Board of the European Science Foundation produced a position paper entitled Marine Biotechnology: A New Vision and Strategy for Europe (see below). This document entirely focuses on promoting the potential of marine biotechnology and has proved influential in shaping the European Union wide Blue Growth Strategy, the EU Horizon 2020 programme and its funding stream entitled Blue Growth: Unlocking the Potential of Seas and Oceans. In short, a focus on potential value can readily be transformed into investments directed to realising potential value. 

In our view the debates on the economic value of marine genetic resources in Areas Beyond National Jurisdiction are primarily about potential rather than actual or realisable economic value. This has important ramifications for the potential design of an access and benefit-sharing component of any implementing agreement within the framework of UNCLOS. Specifically, debates on a possible implementing agreement on access and benefit-sharing for marine genetic resources are directed to the governance of the potential economic importance of marine genetic resources and possible arrangements for benefit sharing. In our view, this suggests that marine genetic resources from ABNJ can be grouped with new and emerging developments in science and technology such as nanotechnology or synthetic biology and debates on climate change adaptation in that they call for anticipatory governance [1,2]. 

In this chapter we examine evidence of actual and potential value for marine genetic resources. We approach this by focusing first on growing interest in the potential of marine biotechnology through a review of two recent reports on marine biotechnology. We then turn to a description of potential markets for marine biotechnology and provide a selection of illustrative examples from our patent data across areas such as lubricants, fuels, catalysts and nanotechnology linked with marine organisms. Finally, we consider the characteristics of trends in marine natural product discovery before turning to data on actual products across a range of sectors. 

6.2 Marine Biotechnology and Potential Value

In this section we briefly summarise two influential reports: The 2010 position paper of the European Science Foundation Marine Biotechnology: A New Vision and Strategy for Europe and the 2013 OECD report Marine Biotechnology: Enabling Solutions for Ocean Productivity and Sustainability. Each report looks at biotechnology from a different angle. The Marine Board of the ESF draws up a road map to develop an EU-wide strategy for future development of marine biotechnology. The OECD considers current trends in biotechnology and how they can be managed for a sustainable future. Figure 6.1 presents a concise summary of the key points raised in these major reports. 

TABLE

	ESF 2010	OECD 2013
Key Arguments	This report argues that marine biotechnology is able to make a significant contribution to global environmental, economic and social challenges.

The report recognises that steps have been taken to better coordinate research infrastructure, but calls for further action to improve collaboration.	This report discusses how marine biotechnology and associated advances in science and technology should be harnessed as solutions to global challenges.

The report calls for a global framework for the sustainable development of marine biotechnology.
Key areas
Food	The reports recognise the significance of molecular technology in aquaculture: using selective breeding, therapeutic methods and enhanced feed to produce a high quality sustainable supply of fish.
Health	The reports recognise the potential of new healthcare products and drugs but acknowledge the challenges of poor taxonomic knowledge, technological limitations and lack of funding for R&D.
Energy	The reports focus on the potential of algal biomass as a sustainable fuel.
Industry	The reports consider marine micro-organisms a sources of ‘greener’ solutions for industrial processes (e.g. enzymes)
Environment	The reports recognise the potential of marine biotechnology to monitor the marine ecosystem (e.g. biosensors) to protect it (e.g. non-toxic anti-fouling agents) and to remediate contaminated environments (bioremediation).
Figure 6.1: Key Points of Marine Biotechnology Reports
 
Figure 6.1: Key Points of Marine Biotechnology Reports (Continued)
	ESF 2010	OECD 2013
Ecosystem
services	Not considered.	Uses a figure of $20.9 trillion per annum as an estimate of the value of marine ecosystem services.  It also recognises services that have no monetary value attached. The report is keen to recognise both the monetary and non-monetary value of ecosystem services provided by the marine environment.
Economic indicators	Not identified.	The report calls for input and output statistics similar to those already used in the pharmaceutical industry. It acknowledges that this will require a common definition of marine biotechnology and will need to factor in a number of socioeconomic indicators e.g. employment. The large scope of this undertaking is recognised by the suggestion that this is trialled initially in a few countries.
Environmental
indicators	Not identified.	The report suggests that the ‘health’ of the ocean be measured using internationally shared indicators that are benchmarked. Such indicators could include measures of biodiversity and pollution.
R&D
priorities	Systematic sampling; culturing methods; cultivation methods; bio-engineering; taxonomic knowledge; information exchange.	Sampling and observation vessels and collection equipment; high throughput screening of genomic sequences; new methods of culturing; new methods of preservation; biobanks and databases; real-time expedition information; taxonomic specialists.
R&D
collaboration	Calls for an urgent EU R&D policy.
This report focuses on the need for specific education and training to equip scientists with the interdisciplinary approaches necessary. 
The report refers to multiple existing coordination networks and notes that the challenge is to build these into a coherent infrastructure.	Recognises the Joint Programming Initiative (JPI) as a model for facilitating cooperation and avoiding duplication. It also identifies a number of bodies offering a similar platform, some of which are international, and others regional; some of which are multidisciplinary and others specialised e.g. focusing only on marine eukaryotes.
Figure 6.1: Key Points of Marine Biotechnology Reports (Continued)
	ESF 2010	OECD 2013
Industry
collaboration	The report recognises the importance of industry-academic partnerships in marine R&D but acknowledges that SMEs currently take most of the financial risks associated with R&D and calls for larger organisations to take a greater role.	The report recognises how globalisation has led to greater collaboration between industry and external partners, particularly academia. It refers to examples of government funding initiatives to encourage such partnerships. It goes on to call for earlier and more focused collaborations, citing the biofuel industry as an example where earlier collaboration has resulted in greater commercial success.
Encouraging
collaboration	The report states that marine biotechnology suffers from a lack of identity in its own right. Like the OECD report, this report suggests that greater public awareness and engagement will raise its profile. The ESF paper gives strong priority to this area of identity and communication.	The report considers the Human Genome Project (HGP) as an example of a successful international initiative, or ‘mega project’ with shared goals.
Access and Benefit- Sharing	This report considers that industry and academia may have different objectives in relation to ABS. It recommends “simplification and harmonisation” of ABS but notes that there are significant issues to be overcome before a mechanism can be established, citing conflicting claims to Arctic waters as an example.	The report provides a descriptive account of current debates around ABS. It discusses the types of ‘benefits’ that may arise, using the Nagoya Protocol and Plant Treaty as a basis. However, the report emphasises that the focus on ABS should not overshadow conservation and sustainability. 
Policy	Both reports call for the alignment of research policy and bioresource policy. They also emphasise the importance of a public engagement strategy. Both are focused on R&D as a priority with ABS as a secondary consideration.

These two reports focus upon and clearly demonstrate the importance given to the marine biotechnology sector by policy-makers and experts. The sector as a whole is regarded as having the potential to play a significant role in the broader arena of biotechnology, both in established medical biotechnology and the newer, emerging field of industrial biotechnology. It is increasingly being presented as a central feature of nations’ bio-economy strategies, offering green economic solutions to some of the major societal challenges of the coming decades.

Potential Markets and Patent Activity

Figure 6.2 provides a brief overview of the major industrial and medical fields of biotechnology. This is followed by illustrative examples of how marine genetic resources have been utilized by various technology fields in patent data. These examples demonstrate the wide range of applications involving marine genetic resources in different technology fields.

Figure 6.2: Summary of some Key Marine Biotechnology Sectors.

Technology Area				
Medical Biotechnology	Pharmaceuticals	Drug Discovery
		Drug Development
		Drug Manufacture
	Medical products	Medical Polymers
		Wound dressings
		Dental Biomaterials
		3D Tissue Culture Scaffolds
		Diagnostic Tools
	Other Health Products	Nutraceuticals
Industrial Biotechnology	Feedstocks	Algal derived biofuels
	Products	Biodegradable Plastics
		Food and Drink Additives
		Cosmetics
		Speciality Chemicals
		Lubricants
	Processes	Enzymes and catalysts
Agricultural Biotechnology	Fertilisers	


Lubricants:

Nissin Oil Mills Ltd and Nippon Steel Corporation (EP0193870A2, 1986) have claimed a new lubricant to be used in the production of steel sheets. The composition of the lubricant included oils from a deep-sea fish found off the coastal waters of South Africa, Australia and New Zealand. The fish used are from Hoplostethus atlanticus, H. mediterraneus, H. gilchristi, and H. intermedius - collectively known as roughies or slimeheads. The oils contain wax esters that have excellent thermal stability, which provide an advantage over other oils when used in a cold rolling environment. This example illustrates the potential for marine genetic resources to be used in industrial processes, but also highlights a conservation issue: the roughy is a late breeding, very long-lived fish, living up to 149 years, which has been an important fishery species. However, over exploitation has seriously reduced the population. Stocks are very slow to recover due to the late age at which the fish breed, which occurs when the fish is approximately 30 years old, and as a result the sustainability of this harvest is in doubt.

Oil recovery:

Another industrial use of deep-sea marine life can be illustrated by a 2012 claim by Geo Fossil Fuels LLC (WO2012116230A1) for “new, efficient, economical and environmentally safe microbial methods to enhance oil recovery, as well as microorganisms useful in such methods”. In this invention microbes that are naturally or engineered to be alkaliphilic, halo-alkaliphilic or alkaline tolerant are used to degrade hydrocarbons in oil reservoirs that subsequently makes the recovery of oil more readily achievable. The microbes that are used contain gene sequences from Oceanobacillus iheyensis, a deep-sea microorganism that was first isolated from deep-sea sediment collected at a depth of 1,050 m on the Iheya Ridge. 

Fuels:

Microorganisms from deep-sea habitats feature prominently in the patent landscape. The Korea Ocean Research and Development Institute claimed in EP2333054A2 (2011) for a novel hydrogenase. This enzyme was isolated from a hyperthermophilic strain of Thermococcus onnurineus, which was isolated from a deep-sea hydrothermal vent at the PACMANUS field in the East Manus Basin of the South Pacific region. Such isolates are deposited in type culture collections, and the source of the strain for this invention was the Korean Collection for Type Cultures (KCTC) at the Korean Research Institute of Bioscience and Biotechnology (KRIBB) where it was assigned the accession number KCTC 10859BP. The claim includes a gene encoding the hydrogenase and the use of a culturing technique for the microorganism to produce hydrogen in a manner more efficient than existing methods such as the electrolysis of water, and the thermal-cracking or steam reforming of natural gas. “According to the hydrogen production methods of the invention, a large amount of hydrogen can be produced merely by culturing the strains in specific culture conditions. Thus, the methods of the invention have advantages in that they are more economic and efficient than existing hydrogen production methods and can produce hydrogen even at high temperature.”
The Craig Venter Institute is involved in similar activity related to producing oxygen-tolerant, hydrogen-evolving hydrogenase and for generating hydrogen from water (WO2008143630A2, 2008). The bacterium used in this example is the Alteromonas macleodii (str deep ecotype, ‘made’) was isolated from deep water (3500 meters) in the Uranian Basin (Crete, Ionian). “Alteromonas macleodii (str deep ecotype, ‘AmDE’) is one of 135 marine microbes sequenced at Venter Institute. It is a gram-negative, heterotrophic marine bacterium that grows under aerobic conditions.”
Yet another marine bacteria offering a potential biotechnological source for production of an energy alternative to fossil fuels is Thermotogae (US20120270297A1, University Bowling Green State, 2012).
Catalysts:
Novozymes AS has made an application to use thermophilic bacteria as a catalyst in the extraction of carbon dioxide (WO2010151787A1), the resulting enzyme having a wide range of potential uses. This application relates to use of carbonic anhydrases obtainable from Caminibacter in CO2 extraction. Carbonic anhydrases are useful in a series of applications, such as for CO2 extraction from CO2 emission streams such as power plants or exhausts and to remove CO2 in the preparation of industrial gases. The carbonic anhydrase or enzyme based bioreactors are also useful in less familiar environments such as in cockpits and fire fighting gear to keep breathing air free of CO2 or to remove from CO2 sensitive environments like museums and libraries to prevent excessive CO2 from causing acid damage to books and artwork.
Several bacterial strains belonging to the genus Caminibacter have been isolated from deep-sea hydrothermal vents. Novozymes’ application describes the cloning, expression and isolation of the mature carbonic anhydrase from C. mediatlanticus DSM 16658 and “confirms that the amino acid sequence gives rise to an enzyme with carbonic anhydrase activity. The characterization of the enzyme also revealed that it is thermostable to a level which could not have been expected based on the growth temperature of the bacterium.”
Polymerases and PCR:
In the fields of biotechnology new uses are being found for extremophilic organisms. In 2009 GE Healthcare Biosciences isolated and cloned a thermostable DNA polymerase gene from Thermococcus barossi, obtained from deep vent flange, Endeavor Segment, Juan de Fuca Ridge, in the U.S.A (WO2009085333A1). The Juan de Fuca Ridge is a tectonic spreading range between the Juan de Fuca Plate and the Pacific Plate. This newly isolated Tba DNA polymerase enabled an improved PCR method for amplifying long DNA fragments. Specifically, this improved method can be used for the rapid amplification of over 10 kb long DNA fragments. The ability to easily and rapidly obtain long DNA sequences was identified as a significant aid to disease gene discovery and analysis. 
The Korea Ocean Research & Development Institute also claim a novel hyperthermophilic “DNA polymerase useful in precision analysis, precision diagnosis, identification and the like, which require accurate PCR” (WO2007043769A1, 2007). In this application, a new hyperthermophilic Thermococcus sp. strain was isolated from a deep-sea hydrothermal vent area at the PACMANUS hydrothermal field located along the crest of Pual Ridge in the East Manus Volcanic Zone, Papua New Guinea. A further example of this organisation’s work with enzymes is WO2008066350A1 (2008) from a Thermococcus sp NAl. strain also isolated from the PACMANUS hydrothermal field.
Another thermostable enzyme, derived from the hyperthermophilic archaeon Thermococcus guaymasensis (isolated from the Guaymas Basin), has utility as a biocatalyst for chiral compound biosynthesis and in biofuel production (WO2010034115A1, Ma Kesen and Ying Xiangxian, 2010). 
Fish Feed & Oils:
Species within the patent landscape that are particularly worthy of note include krill, the small crustaceans of the order Euphausiacea that can be found across the world’s oceans. Krill oils and meal feature in numerous documents and across a variety of industries. One such industry is aquaculture, which is responsible for the supply of much of the fish products consumed by humans. Krill can be used as a component in feed for farmed fish and its use can be illustrated by a 2009 patent application from Nippon Suisan Kaisha Ltd for a “Feed using peeled krill as the starting material and method of preventing decrease in fish growth rate by using the same” (EP2095722A1). The background to this invention is that protein fed to carnivorous farmed fish would normally be in the form of fishmeal, but that the large biomass of Antarctic krill (Euphausia superba) and the increase in scale of the aquaculture industries made krill a potential substitute for fishmeal. The patent claims a composition in which the krill component provides optimum growth rates in the farmed fish, whilst removing the possibility of toxic levels of fluorine entering the food chain by removing the krill’s shell before manufacturing the meal.
Nutraceuticals:
Products manufactured from krill are also consumed by humans, usually in the form of Omega-3 fatty acids provided in what are termed ‘nutraceuticals’, a type of product advertised as having nutritional value as well as having an effect on biological functions. An internet search for krill oil preparations will reveal a large number of marketed products. These products are subject to continual research and development, and a recent example of an invention which hopes to improve the efficacy of a krill supplement is US20120321602A1 (2012) by Ronald E Rosedale in which he developed a new omega-3 function model based on the premise that certain phospholipid forms are better at enhancing membrane fluidity and permeability, while other forms of omega-3 fatty acids (e.g. free fatty acid forms) are better at stimulating biological receptors of interest. Using this model a new product was developed by which the inventor attempted “...to the greatest extent possible, to duplicate at least some of the beneficial effects of caloric restriction as a model for improved health.”
Nippon Suisan Kaisha Ltd has claimed “a sexual function improving agent” that “contains a lipid as an active ingredient, which includes a highly unsaturated fatty acid as a constituent fatty acid” (WO2012103692A1). This agent includes purified krill oil as the active ingredient.
Pharmaceuticals:
Bioprospecting for marine anti-tumour compounds has produced a number of successes, as demonstrated by the table of marketed marine derived drugs (below). Tunicates, also known as sea squirts, have been especially successful in yielding prospective anti-tumour cancer therapies. In 2007 the Spanish company PharmaMar SA claimed for an anti-tumour treatment produced from indole alkaloids derived from the tunicate Aplidium cyaneum (WO2007054748). The tunicates were collected by bottom trawling in the Weddell Sea at a depth ranging between 220 and 300 metres. This species is distributed around the Antarctic in waters of the continental shelf and slope from 75 down to about 1,000 metres. Compounds isolated or derived from tunicates have been and are being subjected to clinical trials and are perceived as being a potentially valuable part of the ongoing search for specific anticancer drugs.
A further relatively recent example of an organism with potential pharmaceutical application is found in WO2011076605A1. In this 2011 application, the French National Centre for Scientific Research (CNRS) and Lille University of Science and Technology claim the use of a deep-sea heat tolerant worm in aquaculture and with potential human pharmaceutical applications. It is claimed that the pharmaceutical composition can be used as an animal or human antibiotic therapy, in a dietary composition, particularly a food supplement, and in disinfectant. An antimicrobial peptide was isolated from a deep-sea worm, Alvinella pompejana. This worm is extremely heat-tolerant, surviving in temperatures up to 80 °C. The applicants disclose that “Twenty entire full-grown and sexually mature Pompeii worms were collected on the East Pacific Rise at 3,000 meters deep”.
Another example of potential pharmaceutical application of a marine derived product is from the mucus of the hagfish, Myxine Glutinosa. In a 2009 application from the Canada National Research Council (WO2009149554A1) the peptide myxinidin in the extract of extruded hagfish slime exhibited microbiocidal activity against a wide range of microbial pathogens and no toxicity to mammalian red blood cells. It is claimed that the antimicrobial peptide myxinidin is useful as an antibactericidal or bacteriostatic agent for the treatment of human and fish pathogens and for promoting wound healing. Atlantic hagfish are most commonly captured in muddy sediments on the ocean floor at depths between 150-250 m but have a much wider range of habitats and have been found at up to 1000 m depth.
Nanotechnology:
An example of a patent application with wide ranging potential across nanotechnology, pharmacology and drug synthesis is WO2005094543A2, Verenium Corp (formerly Diversa Corp), 2005. This example is based on a heat resistant protein Cannulae A (or CanA) that is capable of forming nanotubes. “Cannulae nanotubes are formed by Pyrodictium abyssi, a hyperthermophilic microorganism discovered in a high temperature environment (>100 °C). In its natural environment and in cell culture, Pyrodictium abyssi are linked together by a meshwork of these nanotubular fibers that both connect and entrap the cells.” According to the document, “these fiber networks are a unique feature of the genus Pyrodictium and they appear to be required for growth above 100 °C … While it remains speculative as to what the true role of the nanotubes is in nature, it has been suggested that the linkage of cells by these tubules could enable cells to exchange metabolites, genetic information, or signal compounds.” It is claimed that the potential uses of this application include heat resistant fabrics and coatings, plant growth, detoxification of soil and water and in human health. 
Diagnostics:
WO2001009387A1 from 2001 by Northeastern University from the USA is an example of the use of novel genetic properties of marine organisms in diagnostics. Fish samples were collected from Antarctic waters near Low and Brabant Islands in the Palmer Archipelago by bottom trawling. The inventors discovered that a unique family of Antarctic fish, (the hemoglobin-lacking icefish Chaenocephalus aceratus, Pseudochaenichthys georgianus and Chionodraco rastrospinosus), failed to express hemoglobin, due to deletion of most of the juvenile and adult globin gene complexes. The so-called ‘white-blooded’ icefish also no longer produce red blood cells. The claimed invention is a method for identifying novel hematopoiesis-related genes, especially erythropoiesis-related genes, by screening for and identifying genes that are expressed by red-blooded fish but not by white-blooded fish. The invention is useful for the diagnosis and treatment of diseases such as sickle cell anaemia, thalassemia or clinical anaemia following chemotherapy. 
 
Bioluminescence:
References can be found throughout the patent data to marine genetic resources that are no longer the focus of inventions but have become established and beneficial tools across a variety of technologies and industries. Prominent among these are the fluorescent proteins. These proteins were originally isolated from marine organisms. Green fluorescent proteins (GFPs) have been isolated from the jellyfish Aequorea victoria, the sea pansy Renilla reniformis, and the hydroid Phialidium gregarium. These proteins, which act as energy-transfer acceptors in bioluminescence, function as reporter genes in a variety of molecular or cell biology research techniques. Although originally isolated from Aequorea victoria GFPs have been successfully developed in the laboratory and now include a number of colour variations.
Research carried out to further explore bioluminescence in marine animals can be illustrated by EP1156103A2 in which Chisso Corporation (2001) claimed a polynucleotide or polynucleotides encoding Oplophorus luciferase from the deep-sea shrimp Oplophorus gracilirostris. The invention also included a method for recombinantly producing the proteins by culturing the host cell.
Biosensors:
Some patent activity relates to using deep-sea bacteria to monitor human activity such as disposal of waste in the deep-sea. EP1193312A1 (2002) illustrates the development of a 16S rDNA probe useful for species-specific detection of a microorganism as an indicator in studying and monitoring its growth and the circulation of deep-sea water. The National Institute for Advanced Industrial Science & Technology (Japan) application aimed “to provide a technique for species-specifically detecting a microorganism naturally inhabiting in the deep sea or an analog thereof, based on the characteristics of its genetic information.” Specifically a probe can detect Psychrobacter pacificensis at a molecular or cell level. 
Psychrobacter pacificensis is a heterotrophic microorganism from seawater of the Japan Trench at a depth of 6,000 meters. There are concerns about water quality due to increased CO2 and other pollutants that find their way to deep-layer seawater. The focus of the application is to provide a technique for determining the risks of using deep-sea water and monitoring the health of the deep-sea.
Measuring Biodiversity:
Other patent activity involves the development of probes for measuring biodiversity. In 2003, the Council of Scientific and Industrial Research (CSIR) of India made an application for a probe to detect lantern fish as a measure of biodiversity in the ocean (US20030143534A1). “Among the mesopelagic fishes (200–1000 m), the lantern fishes (Family Myctophidae) are extremely common and numerous in both species and individuals in the open ocean midwaters of the world oceans”. Understanding the population levels and distribution of Myctophids can assist in the assessment and estimation of genetic resources, genetic variability and the level of gene flow between various stocks and populations in the world oceans. The invention applies recombinant DNA techniques to DNA extracted from the lantern fish for the preparation of the genetic probes that can identify specific species of fish.
Biofouling:
Another significant area of patent activity is the development of non-toxic anti-fouling agents. The value of the market for marine hull coatings is estimated to rise from $5 billion in 2011 to $10.2 billion in 2018.  Biofouling is the undesirable accumulation of microorganisms, plants, and animals on artificial surfaces such as ship hulls, docks, buoys, etc. More than 4000 organisms have been reported as being species causing biofouling, including bacteria, micro-algae, macro-algae, sea-grass, molluscs, crustacean, etc. Most fouling organisms have a swimming larval stage followed by a sedentary adult stage that remains attached to its substratum throughout the remainder of its life. The attached adult organisms can increase frictional resistance on the hulls of ships, increase the weight of buoys, block seawater pipes and compete for space and food with cultured shellfish, among other negative effects.
From the 1960s until recently, organotins, represented by tributyltin (TBT), were common anti-fouling agents. TBT is now regarded as one of the most toxic and hazardous compounds introduced into marine environments. The concerns about TBT and other antifouling biocides have resulted in extensive research and development to create non-toxic antifouling coatings.
An illustration of the type of product development and research is provided by the Hong Kong University of Science & Technology (US20110185944A1, 2011) which claims a non-toxic, environmentally friendly method for preventing or reducing biofouling caused by Balanus amphitrite, Hydroides elegans, and Bugula neritina. The application is for antifouling compounds produced from a Streptomyces albidoflavus strain UST040711-291 isolated from a sediment sample from 5000 m depth in the west Pacific Ocean. The product was developed by culturing the bacteria and then extracting a novel group of butenolides (a type of lactone) compounds. These compounds were found to repel various organisms at all stages of their life cycle when applied to a surface. The patent application describes the new compound as well as the production method and method of application.
 
UK Economic Potential of Marine Biotechnology
Translating the potential economic value of marine genetic resources into actual economic value is difficult. However, it is also important to recognise that biotechnology as a whole has followed a trajectory or pathway from potential to actual value over the last 30 years. While biotechnology as a sector continues to depend on promises of future products, the pursuit of potential has also translated into the creation of new companies, jobs and contributions to GDP. The UK biotechnology sector and markets for biotechnology products provides a good indication of this trajectory. 
The UK Department for Business, Innovation and Skills, publishes an annual report relating to the landscape of medical and industrial biotechnology and the pharmaceutical sectors in the UK [3]. The annual report provides a snapshot of the state of the various UK biotechnology related sectors and how they are performing in global markets. Marine biotechnology does not feature in these reports, however, as we have seen in earlier chapters, marine genetic resources may contribute in various ways to activities and products developed in these technology areas.
According to UK government figures the three biotechnology related sectors employ approximately 122,000 people in the UK dominated by the pharmaceutical sector and followed by the medical biotechnology sector with 50,000 employees. The industrial biotechnology sector in the UK remains small, and employs approximately 1,800 people. The combined biotechnology sector in the UK has an annual turnover of over £38 billion.
Medical Biotechnologies Market
In the UK this sector employs nearly 27,000 people in 1,073 companies with a turnover of £4.2bn in 2012-2013. A third of these companies undertake R&D dominated by drug discovery and antibody and small molecule technologies. In addition to this core business there are a number of companies providing products and services, and this specialist services sector comprises 903 companies and employs 23,350 people. The total sector growth between 2009 and 2013 was 22%, but this was also marked by a 3.1% drop in employment. The majority of the companies in this sector are Small and Medium Sized Enterprises (SMEs) [3]. 
Global sales of biotechnology based pharmaceuticals were estimated at £105bn in 2012. Biologics account for 39% of global sales when the analysis is restricted to the top 100 selling drugs. The report estimates that 25% of all pharmaceutical sales will come from biotechnology based products by 2018 representing £130-£190bn [3]. 
 
Industrial Biotechnology Market
In the UK this sector employs approximately 1,790 people in a core group of 121 companies with an annual turnover of approximately £605m. Most companies employ less than 250 people and this is regarded as an emerging sector. Businesses within this sector mainly focus on biofuels, food and drink products, and specialist services that provide reagents and equipment. The largest of these companies specialise in enzymes and associated technologies. The global market value for industrial biotechnology in 2011 was estimated at £32bn. In Europe industrial enzymes are of significant importance and the global market for these products is estimated at £1.9bn. Biofuels using feedstock of corn, sugar cane and wheat are particularly important in the Americas with the USA as the main market [3]. 
Pharmaceutical Market
This is the largest of the three UK biotechnology sectors, with a turnover of £29bn and employing 70,300 people in the UK. 477 companies operate in this sector in the UK. 182 companies (excluding global top 20 companies) are concerned with drug discovery, development and manufacture of pharmaceuticals, employing 16,400 people. 189 specialist supply companies employ 6,200 people and provide clinical trials, equipment, production and regulatory services. Between 2009 and 2013 the workforce fell by 2.7%, driven by the 20 top global companies. Elsewhere the sector saw growth in employment and turnover [3]. The global market for medicines is predicted to grow to £770bn by 2016 with up to £256-275bn of this coming from over-the counter medicines. 
As this makes clear, the biotechnology sector in the UK has emerged as a significant source of employment and increasingly makes an important contribution to the UK economy. What remains unclear, and will remain unclear for the foreseeable future, is the contribution that marine biotechnology will make to these sectors. As the OECD has recently highlighted, one reason for this is that in contrast with areas of biotechnology that focus on products and markets (e.g. health, industrial and agriculture), marine biotechnology does not focus on a particular market but is defined by the origin of organisms and genetic material [4]. The assessment of the actual or potential contribution of marine biotechnology to the UK economy would therefore depend on the ability to identify when marine organisms and genetic material are used and to quantify their final contribution to production and market sales. 
Having considered issues around the potential value of marine biotechnology we now focus on trends in research on marine natural products as a basis for examining available data on marketed products and market values. 
 
6.3 From Potential to Actual Value
Marine natural products are the focus of regular annual reviews in peer reviewed journals such as Natural Products Reports [5] and Marine Drugs [6]. Annual reviews typically focus on providing details of new compounds from marine organisms and, in some cases, the status of compounds in the clinical pipeline and approval process. In other cases specialist reviews focus on topics such as anti-cancer agents or classes of marine organisms such as invertebrates or macroalgae [7-9]. The specialist MarinLit database, developed at the University of Canterbury in New Zealand and now operated by the UK Royal Society of Chemistry, lists 24,000 compounds and 26,000 scientific articles.
These reviews provide invaluable information on trends in marine natural products research. However, in some cases the precise source organism for a compound or set of compounds is unclear. This presents problems for determining the origin of marine genetic resources inside the EEZ or from Areas Beyond National Jurisdiction. There are in fact good reasons for this. As one important recent review explains: 
“We will also avoid using the source organism as the method of classification as it is now becoming quite evident that the majority of compounds reported from the marine environment are in fact produced by, or in concert with, single-celled organisms ranging from protists (frequently dinoflagellates) to bacteria, including a very significant number of as yet uncultured organisms.” (Newman and Cragg 2014: 256)
In short, marine compounds of interest for pharmaceutical development may arise from organisms hosted by other organisms or existing in a symbiotic relationship with other organisms. This complicates efforts to link particular compounds to a specific organism and particular places in the EEZ or ABNJ. 
Recent reports reveal that since the 1960s more than 20,000 compounds have been discovered in marine organisms [10,11]. Prior to 1985 less than 100 marine natural products were described each year. However, with the advent of high speed nuclear magnetic resonance spectrometry (NMR), enabling easier identification of chemical structures, this situation changed significantly from the mid-1980s onwards with a fairly constant 500 new marine compounds described per year between 1990 and 2006 [10]. The main sources of new compounds between 1985 and 2008 were marine invertebrates such as sea sponges and corals with over 300 compounds per year described from 1995 to 2008 [10]. Marine algae have been the source of between 50 and 100 new compounds per year between 1985 and 2008 while microorganisms, including phytoplankton, rose from approximately 50 per year to just over 100 compounds per year between 2007 and 2008 [10]. Hu et al., (2011) state that up until 2008 “approximately 75% of the compounds were isolated from marine invertebrates belonging to the phyla Porifera (mostly sponge) and Coelenterate (mostly coral)” and remained constant between 1985 and 2008 (Hu et al., 2011: 517). In short, the substantive increase in interest in marine natural products reported in the literature is concentrated in a relatively narrow spectrum of organisms.
Research by Leal et al., (2012) on marine invertebrates as a source of 9,812 new natural products between 1990 and 2009 identifies trends in marine compounds from invertebrates and maps the data by the sources of compounds by EEZ [8]. Figure 6.3 displays the major trends for invertebrate phyla.
 
Figure 6.3: Trends in Natural Products from Invertebrates (doi:10.1371/journal.pone.0030580.g001)
Figure 6.3 displays trends in new natural products from marine invertebrates by phyla and demonstrates that the majority of new marine natural products are from Porifera and Cnidaria [8]. However, they highlight that since 1990 the majority of research has “focused on less than 1% of biodiversity currently recognised for marine invertebrates” (Leal et al., 2011: 5). In short, biodiscovery efforts are focused on a narrow segment of marine invertebrates. Figure 6.4 reproduces the results of research to map the distribution of new natural product discoveries from invertebrates by EEZ and also displays biodiversity hotspots for invertebrates [8].
 
Figure 6.4: New Natural Products from Invertebrates by EEZ (doi:10.1371/journal.pone.0030580.g004)
Figure 6.4 presents the number of new natural products from marine invertebrates during the 1990s and from 2000–2009 including the EEZ boundaries and markers for biodiversity hotspots [8]. In seeking to explain the concentration of marine biodiscovery research in sponges and cnidarians (corals) they argue that this could be explained by their accessibility and the wide distribution of the target species. We would note that Leal et al., do not specifically address the subject of Areas Beyond National Jurisdiction. However, the available data on the distribution of invertebrates that have been the source of new natural products strongly suggests that they mainly occur inside the EEZ in coastal areas for the straightforward reason that they are accessible. 
This does not mean that deep-sea natural products are not a focus of research effort. However, organisms from the deep-sea may be somewhat hidden in major reviews focusing on the description of compounds. The most detailed review of natural products from the deep-sea that we have been able to identify is the work of Danielle Skropeta from Wollongong University in Australia [12]. Skropeta’s review focuses on species recorded at depth, rather than Areas Beyond National Jurisdiction, and identifies 390 marine natural products ranging in origin from Antarctica to the Caribbean and Atlantic. Over 50% of the metabolites identified in the review were drawn from depths between 100-400 metres, with 10% from 500-600 metres and 8% below 1000 metres [12]. At the time of the review the deepest reported sample came from deep ocean sediment at 5065 metres in the Central Pacific Basin and involves an unidentified gram-positive bacterium that produces two cytotoxic compounds [12]. In common with the wider literature the review highlights that “Deep-sea sponges are by far the largest source of new deep-water metabolites, accounting for over 60% of those reported to date” at depths up to 1,000 metres, with echinoderms accounting for 15% of natural products to depths of 2,000 metres followed by microorganisms at 12% at depths up to 5,065 metres (Skropeta 2008: 1158). A review of the Marine Drugs journal for references to the deep-sea in the title, abstract or author keywords of articles revealed 31 new publications with 14 published in 2013 suggesting growing interest in deep-sea organisms. Given that this is confined to one journal it will represent an underestimate of wider publications. 
As this makes clear, while there has been significant growth in interest in marine organisms as a source of new natural products this displays very particular characteristics with respect to a focus on coastal areas and marine invertebrates. We now turn to a discussion of the obstacles involved in developing marine natural products before considering data on actual products on the market and their origins. In this discussion we draw primarily on the most recent 2014 review of marketed marine natural products by Ana Martins et al., and complement this information with the results of our own research [13]. We would note that the evidence base for widely quoted market estimates is not generally accessible for validation. 
Barriers to the Development of Marine Products
Martins et al., (2014) focus on the pharmaceutical and cosmeceutical (medical cosmetics) market and identify three main barriers to commercial success: a) accessibility of the biodiversity; b) supply and technical issues (sustainable production), and; c) the cost of bringing a product through to market [13].
The extent of these barriers comes into focus when we consider that approximately 20,000 structurally unique marine natural products have been described, with 1,241 being described in 2012 alone [13]. However, there are currently only eight approved drugs from marine natural products on the market (one of which, Vidarabine, has subsequently been withdrawn), and another ten in clinical trials [13]. At present, seven cosmeceuticals from marine natural products are commercially available [13].
Factors identified as key barriers for the development of marine natural products in the Martin review and the wider literature include: 
1. Lack of taxonomic knowledge to reach an unambiguous taxonomic classification [13];
2. Variation in the nature of organisms across a species resulting from varying environmental stresses and other factors including the microbial environment [13];
3. Problems with culturing organisms;
4. Problems with obtaining a sustainable supply;
5. Low success rates in clinical trials (a common factor across compounds).
In considering these and other relevant barriers in relation to marine genetic resources from Areas Beyond National Jurisdiction it is logical to add the financial, logistical and technological costs and challenges involved in collecting and culturing organisms particularly at depth. While metagenomics is an important emerging area in marine research the ability to identify a DNA, RNA or amino acid sequence is not the same as the ability to identify a complex compound that is an expression product of multiple genetic interactions and environmental factors for which the ability to sample and culture the organism will be vital. In short, the barriers to the development of marine natural products from Areas Beyond National Jurisdiction, particularly at depth, are significant. 
Marketed Pharmaceutical Products
Having considered some of the challenges facing developers who wish to bring a new product into the marketplace we now turn to those products that have become commercial products, taking in pharmaceuticals that have been approved as well as enzymes, nutraceuticals and other products. A number of the products presented below have been described in earlier research on marine genetic resources in Areas Beyond National Jurisdiction or in the marine natural products literature [11,14]. Here we focus on information provided by Martins et al., (2014) and add additional information from a range of sources including company websites. 
Figure 6.5 below, presents the approved pharmaceutical products presently being commercially marketed. This is followed by brief descriptions of the development history and uses for each product. One approved product, Vidarabine, was withdrawn following approval and is not shown [13].
 
Figure 6.5: Approved Commercial Marine Pharmaceutical Products
Product Name	Type	Species Name	Manufacturer	Sector	Market Value
Cytarabine (Cytosar-U®, Depocyt® & Tarabine PFS®)	NP	Cryptotethya crypta	Bedford (USA)
Enzon (USA)
Pfizer (USA)	Cancer	 $93 million
(2007) 
Ziconotide
(Prialt®)	NP	Conus magus	Perrigo (IR)	Neuropathic pain	$29 million (2011) 
Omega-3-acid ethyl esters
(Lovaza®)	NPD	Omega-3-acids/fish	GlaxoSmith-Kline (UK)	Hyper-triglyceridemia	$975.8 million (2013) 
Trabectedin (Yondelis®)	NP	Ecteinascidia turbinata	PharmaMar (ES)	Cancer	€73 million (2013) 
Eribulin mesylte (Halaven®)	NPD 	Halichondria okadai	Eisai (JP)	Cancer	€200 million (2012) 
Brentuximab vedotin (Adcentris®)	NP	Dolabella aucicularia	Seattle Genetics (USA)
Takeda GRDC (JP)	Cancer	$145 million (2011) 
Iota-carrageenan (Carragelose®)	NP	Eucheuma/
Cnondus	Marinomed (AUT)
Boehringer Ingelheim (D)	Antiviral	 Not available

NP = Natural Product. NPD = Derived from Natural Product
 
We now turn to a brief description of each approved pharmaceutical. 
Cytarabine (Cytosar-U) Bedford (Bedford, OH, USA) and (Depocyt), Enzon (Piscataway, NJ, USA)
Cytarabine is an agent used mainly in the treatments of cancers of white blood cells such as acute myeloid leukaemia (AML) and non-Hodgkin’s lymphoma. It kills cancer cells by interfering with DNA synthesis. Having been discovered in a Caribbean Sea sponge Crytotethia crypta, cytarabine was first synthesised in 1959 and was approved by the FDA in 1969. It was initially marketed in the U.S. by Upjohn under the trade name Cytosar-U. DepoCyt is a slow-release form of cytarabine. Forty-five years after its approval, cytarabine is still at the forefront of cancer treatment [13].
Ziconotide (Prialt), Elan Corporation (Dublin, Ireland)
Prialt was granted approval for the management of severe chronic pain in 2004, Ziconotide having been synthesised in 1987 after the isolation of a peptide from the venom of the cone snail Conus magus, known as a conotoxin, originally collected from Indonesia. The process from discovery to approval took over thirty years. Ziconotide induces a blockade in the spinal cord that inhibits the release of pain-relevant neurotransmitters [13]. Other conotoxins are in various stages of development.
Omega-3-acid ethyl esters (Lovaza), GlaxoSmithKline (Brentford, UK)
Lovaza (formerly Omacor) was developed by Reliant Pharmaceutical and commercialised by GlaxoSmithKline. It is an anti-hypertriglyceridemia drug with omega-3 fatty acids sourced from fish oils.
Vascepa (Amarin, Ireland) was granted FDA approval in 2012 and is a major competitor to Lovaza, although it generated only $26 million in its first full year of sales. Amarin is currently in dispute with the FDA over the limited exclusivity rights they were granted for the product. 
With sales of Lovaza approaching $1 billion, drugs from fish oils form a lucrative market.
Trabectedin (Yondelis), PharmaMar (Madrid, Spain)
Trabectedin (ET-743, Yondelis) is an anti-tumour agent. It was discovered in the colonial tunicate Caribbean sea squirt Ecteinascidia turbinata and is currently produced by chemical synthesis. Yondelis received FDA approval for treatment of advanced or metastatic soft tissue sarcoma in 2007 and in November 2009 received marketing authorisation from the European Commission for the part treatment of ovarian cancer. Yondelis has been designated an orphan drug by the European Commission and the FDA for soft tissue sarcoma and ovarian cancer. Phase II trials are also being carried out for breast cancer and for paediatric tumours. Another Phase III trial is reported to be ongoing for soft tissue sarcoma in first line treatment. 
Development of trabectedin was hampered by E. turbinata having a very low yield (0.0001%). Sufficient quantities for development were ensured by cultivating the tunicate, however this was impractical for commercial scale production and there remained significant problems with industrial manufacture until a semi-synthetic route was developed in 1996 [13].
Eribulin mesylate (Halaven), Eisai (Tokyo, Japan)
Halaven gained FDA approval for metastatic breast cancer in 2010. Halichondrin B was first isolated in 1986 from the sponge Halichondria okadai. Once again, the problem of insufficient yield hampered development until synthesis was achieved in 1991, followed by the development of a simplified analogue, Eribulin mesylate. Halaven fights cancer by inhibiting tubulin, a protein component of the cytoskeleton that is needed to support the rapid growth of cancer cells [13]. Halaven has recently been granted approval for the Russian market. 
Brentuximab vedotin 63, (Adcetris), Seattle Genetics (Bothwell, WA, USA)
Adcetris is the first new treatment for Hodgkin’s lymphoma for over thirty years. It won FDA approval in 2011 after a development period of forty years. Brentuximab vedotin 63 is based on a fully synthetic analogue of dolastatin 10, isolated from the sea hare Dolabella auricularia in 1972 [13] and later from the cyanobacteria Symploca hydnoides and Lyngbya majuscula which are part of the sea hare’s diet [13].
Adcetris is currently approved as a treatment for relapsing, post chemotherapy Hodgkin's lymphoma patients. It is also approved as a second-line treatment for anaplastic large-cell lymphoma (ALCL).
The drug has captured 70% of these markets, generating nearly $145 million in sales in 2013. Seattle Genetics estimate that the drug has potential to make up to $1b pa through expanding its use and has gained FDA orphan designation for large B-cell lymphoma (DLBCL).  
Iota-carrageenan (Carragelose), Marinomed Biotechnologie GmbH, (Austria)
Carragelose is an anti-viral nasal spray for use against early symptoms of the common cold by creating a protective anti-viral barrier in the nasal cavity. The active component, a linear sulfated polysaccharide, was extracted from red edible seaweeds, mainly Rhodophyceae. Carragelose is an over-the-counter drug.
 
Marine drugs in clinical trials
Martins et al., identify ten marine derived pharmaceuticals in clinical trial stage, one at Phase III, four at Phase II and five at Phase I. A further 18 potential products were discontinued during clinical trial phases.
Spanish marine biotechnology company PharmaMar is closest to marketing the next marine derived drug, Aplidin, an antitumour agent originally isolated from the marine tunicate Aplidium albicans, and now obtained by chemical synthesis. Aplidin is currently in phase II clinical trials for solid and haematological malignant neoplasias like T cell lymphoma and in phase III clinical trials for multiple myeloma.
The FDA has accepted the proposal made by PharmaMar for the production process of the drug and it has been designated an orphan drug by the European Commission (EC) and the FDA for multiple myeloma (MM).
According to the company’s website, one third of all scientific patents and publications on anticancer drugs of marine origin are the result of the research carried out by PharmaMar. 

Potential pharmaceutical applications of marine natural products

One of the most significant areas of research for potential applications of MNPs is in substances with cytotoxic or anti-tumour properties. Organisms yielding potential compounds are a diverse group of marine animals, algae, fungi and bacteria [11]. The recent success of Yondelis, Halaven and Adecterin show the potential of this area of research.

Other areas of interest relate to treatments for pain and for HIV-Aids and other infectious diseases such as malaria, with sponges and marine fungi being widely used in these areas of research. Anti-inflammatories and anti-coagulants are other substances that may be developed from MNPs.

Cosmeceuticals

Cosmeceuticals blur the boundaries between cosmetics and pharmaceuticals. Anti-oxidants and anti-ageing products are in great demand, with a trend for those containing biologically active marine components derived from coastal plants, seaweed, algae and sea minerals [13]. Many of these products are high-end prestige products such as Creme de la Mer (Estee Lauder) retailing at £350 per 100 ml.
Cogent Skills for Science Based Industry estimate the global cosmeceutical market to be worth $30 billion (2011) and predicts the UK cosmeceutical market will be worth £2.17 billion by 2016. These figures include all cosmeceuticals, not just those derived from MNPs. However, being the fastest growing sector of the personal care industry, with a predicted annual growth rate of 7.7%, it is evident that those with MNPs will be subject to increasing demand. 
Many new cosmeceutical products have potential applications in the pharmaceutical arena. However, cosmeceuticals are a quicker, less expensive route to market. 
The marine environment contains a wide variety of ingredients valuable to the cosmeceutical industry: polyunsaturated fatty acids (PUFAs), polysaccharides, vitamins and minerals [13]. Algae and sea mud are established sources of products such as the Oceanwell range of Baltic Sea aqua-cultured algae (OceanBasis, Germany) and the Fanghi d’Alga GUAM range based on seaweed from Guam (Lacote, Italy).
Microalgae extracts are incorporated in many skin care, sun protection and hair care products and are the source of recent advances in skin care technology, for example Dermochlorella DG (Codif, France) and XCELL-30 (Greensea, France) which act on the epidermal layer of the skin and Alguronic Acid (Algenist, CA, USA) and Alguard (Frutarom) which are protective anti-ageing products.
The following selection of recently launched or high profile products illustrates their marine origin.
Abyssine (Kiehl’s, New York, USA owned by L’Oreal)
EPS (exopolysaccharide) compounds are one of the most common molecular classes in personal care bioactives. Various marine microorganisms including proteobacteria, cyanobacteria and archaea produce EPS. Abyssine contains EPS HYD657 (deepsane) secreted by Alteromonas macleodii subsp. fijiensis biovar deepsane, which was collected from a polychaete annelid Alvinella pompejana close to a hydrothermal vent at 2600 m depth on the East Pacific Rise in 1987 [13]. Abyssine is marketed as a treatment for sensitive skin [13].
Resilience (Estée Lauder, New York, USA)
The Resilience skin care product range contains an extracellular extract from the Caribbean sea whip Pseudopterogorgia elisabethae (Gorgoniidae), the extract being mainly composed of pseudopterosins which are potent anti-inflammatory and analgesic agents. Pseudopterosins were previously trialled as wound healing agents. Resilience is marketed as effective in preventing irritation due to exposure to the sun or chemicals [13].
SeaCode (Lipotec, Barcelona, Spain)
SeaCode contains an exocellular polysaccharides (EPS) from a Pseudoalteromonas sp. isolated in intertidal coasts of Antarctic waters. Seacode is marketed to significantly enhance synthesis of key dermal proteins (collagen I) and reduce skin roughness. Lipotec produces a number of marine derived cosmetic skin care products in addition to Seacode, such as Antacticine and Hyadisine. 
RefirMAR (BIOALVO, Lisbon, Portugal)
RefirMAR is a natural ingredient derived from an intracellular extract of a new bacterial strain of Pseudoalteromonas sp. isolated at a depth of 2300 m at the Rainbow hydrothermal vent in the Portuguese EEZ section of the Mid-Atlantic Ridge (MAR) near the Azores islands.
The ingredient displays activity similar to botulinum toxin A, inhibiting localised muscle contraction and is therefore marketed as an anti-wrinkle agent which has the advantage of topical application over competitor products which need to be injected.
BIOALVO has a number of other marine based cosmeceuticals in late stages of development. SunMAR and OxiMAR (an anti-oxidant) are both based on a set of strains isolated at hydrothermal vents in the Azores islands. In addition, the company is developing pharmaceuticals from strains isolated at the same source. BIOALVO state that they have 140 individual new strains isolated from hydrothermal vents in the Mid-Atlantic Ridge in their PharmaBUG library. 
Marine Microorganisms in Nutraceuticals
A nutraceutical is a food product that contains ingredients, recognised as being safe, which aim to prevent chronic disease. It has been estimated that the global market for nutraceuticals, or functional foods as they are also known, will exceed US$243 billion by 2015 [15]. Marine organisms are considered as good potential candidates for use in nutraceutical products due to their adaptations to extreme environments that result in them producing unique metabolites. Within the diversity of microbial marine species are compounds possessing a wide range of pharmaceutical uses [15]. A consideration for the use of marine organisms is whether the organism is ‘food-safe’. For many known microbes this can be based on historical information - where a food has been consumed for generations with no toxicological effect it is considered safe. With many new marine microbial ingredients, however, this sort of information is rare. In some cases, such as traditional fermentation of fish, such data has been available, but it remains important for researchers and relevant authorities to focus on safety for the future development of these products. Some of the bioactive ingredients with potential as nutraceutical ingredients are as follows.
1. Carbohydrates
Exocellular polysaccharides (EPS) are a potentially valuable product of microbes as they are constantly generated and easy to isolate and considered superior to plant polysaccharides [15]. They also have structural diversity, even within closely related phylogenetic strains. Some of these EPS are known to be immune-boosters, and others have potential to defend against tumours and metastasis. Laboratory tests have shown that EPS from marine lactic acid bacteria have very long lasting effects and are considered to be GRAS (generally recognised as safe) [15].
2. Polyunsaturated Fatty Acids (PUFA)
Well-known marine sources of PUFA include fish species such as herring, mackerel and sardines. A problem with some of these as commercial products is heavy metal contamination and an unpleasant taste, and so attention is now turning to microorganisms as the primary producer [15]. A large number of microorganisms have been identified as producers of PUFA, some of which are not suitable for commercial production due to the cost of advanced fermenters. Good candidates are heterotrophic algal species that can be grown in conventional fermenters. Additional research is being carried out into marine bacterial, fungal and yeast sources. 
3. Pigments
Microbial bioactive pigments have recently received attention in nutraceutical products [15]. A number of carotenoids are produced by marine species such as ß-carotene, which is produced by the microalgae Dunaliella salina and is seen as a potentially useful source as it is already produced and used in cosmetics and dietary supplements [15]. Marine bacteria and fungi are also recognised as being producers of bioactive pigments. Some of these however, such as the fungus Monascus purpureus, are still not accepted as being toxicologically safe.
4. Proteins and Peptides
Many marine microalgal species are considered excellent sources of protein, being very productive, high quality, and with potential for nutraceuticals [15]. In the development of therapeutic proteins, marine microalgae have many cost advantages over traditional cell culture. In addition to proteins, bioactive peptides derived from the proteins have potential for disease risk reduction. These come from species such as Chlorella vulgaris and Spirulina platensis. 
5. Probiotics
Live microorganisms can have a beneficial effect for human gut flora by suppressing the activity of disease causing bacteria. The microorganisms are referred to as being probiotic (probiotics being those which enable changes in the gut flora composition leading to health benefits). Probiotics are familiar in existing dairy products such as yoghurts. Research into the use of probiotics in aquaculture are finding that Lactobacillus paracasei is of potential use in fish where resistance to antibiotics has become established and this research has potential to find probiotics for use in humans [15]. 
The development of marine species to provide functional ingredients in nutraceuticals is a new field with current research being carried out through in vivo and in vitro studies. As yet these studies are not sufficient to enable their use in food products. There are legal barriers to be surmounted, notably that the products are recognised as being safe. In such a new field the established criteria of historical use cannot be applied and standards have not yet been defined. Additionally, advances in fermentation technologies will be necessary for cost effective commercial production.
Deep-Sea Derived Enzymes and Proteins
A number of marine enzymes, particularly those from extremophiles, are proving to be useful biocatalysts with a number of industrial applications. Figure 6.6 shows a selection of these products and illustrates the industrial sectors to which they apply.
Figure 6.6: A Selection of Commercially Available Enzymes
Product Name	 	Species Name
(where known)	Manufacturer	Sector	Market Value
Fuel-zyme	Enzyme	 	Verenium (USA)	Ethanol Production	Total market value $100m+ 
Pyrolase	Cellulase Enzyme	 	Verenium (USA)	Industrial Hydrolysis	 Not available
Deep Vent	DNA Polymerase	Pyrococcus sp	New England Bio Labs Inc (USA)	PCR	 Not available
CellLight	Green Fluorescent Protein	Aequorea victoria	Life Technologies (UK)	Biotechnology	 Not available
Product Ingred-ient	Ice Structur-ing Protein	Zoarces americanus	Unilever	Foods	 Not available
MF59	Squalene	Deep-sea shark liver oil	Novartis	Pharmaceut-icals, adjuvant in influenza vaccines	 Not available

Fuelzyme (Verenium, USA) is a high performance enzyme for the liquefaction of starch-based mashes and slurries for use in fuel ethanol production. Verenium also markets Pyrolase and Pyrolase HT, broad-spectrum enzymes with varied industrial applications, useful for the breaking (or hydrolysis) of beta-linked carbohydrates such as guar gum. Verenium estimates the addressable market in the U.S. for guar breakers in hydraulic fracturing is up to $250 million, of which currently marketed enzyme products address approximately 10% or $25 million. The company believes Pyrolase HT represents an advancement in performance properties that can expand the share of this market addressable by enzymes beyond the current estimated ten per cent.  Fuelzyme and Pyrolase were both sourced from hydrothermal vents.
Deep Vent (New England Bio Labs Inc, USA) was sourced from an E. coli strain that carries the Deep Vent DNA Polymerase gene from Pyrococcus species GB-D. The companies website highlights that “the native organism was isolated from a submarine thermal vent at 2,010 meters and is able to grow at temperatures as high as 104°C”.  Deep Vent is used in Polymerase Chain Reactions (PCR), a means to amplify DNA. It has been estimated that polymerase from hydrothermal vents represents 30% of a $500 million annual global market. 
CellLight (Life Technologies, Thermo Fisher Scientific) is a range of reagents to label specific structures in live cells with fluorescent proteins.
Other Natural Resources
Other key commercial products derived from marine organisms include fish oils, krill meal and oils and seaweeds. These three products have significant economic value, and their markets are briefly discussed here and summarised in Figure 6.7.
The increasing demand for Omega-3 products has seen the market for human consumption of fish oils increase, and this market is expected to increase still further as people incorporate Omega-3 into their regular diet. The principal market for fish oils, however, is that of feeds for the aquaculture industry. This accounts for more than 70% of the current market.  The ability to sustain supplies is under pressure due to fluctuating stock levels during El Niño periods. 
The krill harvest is estimated to be at around 150,000 to 200,00 tonnes per year. As with fish oils, the majority of the harvest is directed at aquaculture feeds with a growing demand for human consumption. Krill prices have been steadily rising over recent years, averaging about $1,500 per tonne with some lots reaching as high as $2,250. 
Seaweeds are largely farmed and used for a variety of products with an estimated commercial value of US$ 5.5-6 billion. Most of this ($5 billion) is used as human food products. The remaining market is largely taken up with production of hydrocolloids, used as thickening and gelling agents, with fertilizers and animal feed taking a small proportion. The farming of seaweed has expanded rapidly as demand has outstripped the supply available from natural resources. 
 
Figure 6.7: Other Commercial Marine Natural Resources.
Product	Uses	Scale of Harvest	Value of Market
Fish Oil	Used as aquaculture feed (about 70%) and as human health supplement (Omega-3 fatty acids).

Peru, Chile and Denmark are major players. Human consumption rising but demand likely not to rise due to factors such as El Nino which causes fluctuating harvests	Demand –1,035 kilotons (2011) rising to 1,130 kilotons in 2018.	US$ 1.1 Billion (2011) expected to reach US$1.8 billion by 2018. 
Krill Oil and Krill Meal	Used as aquaculture feed and as human health supplement (Omega-3 fatty acids).

Harvesting of krill in the Antarctic licensed by Commission for the Conservation of Antarctic Marine Living Resources (CCAMLR).	Global Harvest 150,000 - 200,000 tonnes. Average E. superba harvest in Antarctica is 130,000 tonnes against a CCAMLR catch level of 620,000 tonnes.	Krill meal price US $1,500 per ton.
Krill oil price US $7.5–30 per kg. 
Pharmaceutical grade oil higher price.
Seaweeds	Food, cosmetics and toiletries.

Fertilisers.

Industrial source of phycocolloids.	Total harvest of 14.7 million tonnes. 88% of commercial seaweeds are farmed.	Total market for seaweed products estimated at US $6 billion. 

 
6.4 Conclusions
This chapter has provided an overview of the available data on the economic value of marine genetic resources with a particular focus on marine genetic resources from Areas Beyond National Jurisdiction. Our main conclusion is that at present the economic value of marine genetic resources from the deep-sea can best be described as potential value. The reason for this is that, based on available information, the majority of research on marine natural compounds is targeting a limited number of marine invertebrates that predominantly occur in national jurisdictions. While there is growing interest in marine natural products from deep-water areas inside and outside of national jurisdictions it is fair to conclude that the majority of interest focuses on coastal areas by virtue of their accessibility. Furthermore, and with the notable exception of a number of enzymes and omega-3 products involving krill, there is limited evidence of marine genetic resources from Areas Beyond National Jurisdiction on the market. Overall, a major limitation of existing data on the economic value of marine genetic resources is that current economic values are purely indicative. As we have also noted, existing estimates of the actual or potential market value of marine genetic resources are affected by a lack of methodological transparency. 
As such, marine genetic resources from Areas Beyond National Jurisdiction primarily fall into the category of potential value. This is important for two reasons:
1. It is important that debates on a possible implementing agreement on access and benefit-sharing do not conflate estimates of potential value with actual value. In our view the conflation of potential value with actual value would probably lead to a highly restrictive agreement that would negatively and unnecessarily restrict marine scientific research and prevent the realisation of the potential economic value of marine genetic resources.
2. A growing number of countries and regions, notably the European Union, are developing strategies for the development of marine biotechnology. These strategies are directed to the realisation of the economic potential of marine genetic resources and, in the case of the work of the OECD, identify important issues for consideration in the development of a forward looking implementing agreement directed to realising the potential of marine genetic resources and contributing to conservation and sustainable use. In particular calls from the OECD for a global framework for the development of marine biotechnology have parallels with calls from the marine scientific community considered in the next chapter for a more strategic multi-decadal approach to marine scientific research in the deep-sea. While recognising the different drivers behind these proposals in our view any implementing agreement involving access and benefit-sharing could include a forward-looking framework plan on marine genetic resources.
It is important to recognise that the practices for the collection and use of marine genetic resources for different sectors identified in this chapter are likely to have different environmental impacts. For example, the use of benthic trawls for the collection of marine invertebrates or the large scale commercial harvesting of Antarctic krill have very different environmental impacts than small-scale collection of sea water or sea floor sediments. These issues are discussed in more detail in the next chapter on expert perspectives but need to be seriously considered in debates on any potential implementing agreement involving access and benefit-sharing. 
Finally, the conclusion that the economic value of marine genetic resources from Areas Beyond National Jurisdiction primarily fall into the domain of potential value leads us to conclude that the most appropriate model for the governance of these resources under any implementing agreement is likely to require anticipatory governance. Put in simple terms, any implementing agreement would identify the international measures necessary to realise the economic potential of marine genetic resources from ABNJ while ensuring the conservation and sustainable use of marine genetic resources. That is, an agreement would anticipate, facilitate and enable the realisation of the potential economic value of marine genetic resources. 
The concept of anticipatory governance is relatively recent and is increasingly applied to emerging trends in science and technology, notably nanotechnology and synthetic biology, public administration and environmental policy [1]. It is also increasingly applied to planning for adaptation to climate change. While the literature varies in its emphasis, Fuerth [16,17] defines anticipatory governance as follows: 
“Anticipatory Governance is a system of institutions, rules and norms that provide a way to use foresight for the purpose of reducing risk, and to increase capacity to respond to events at early rather than later stages of their development.” (Fuerth 2009: 29)
Key elements in anticipatory governance include: a) anticipation and futures analysis; b) the creation of flexible adaptation strategies, and; c) monitoring and action [2]. This can also be expressed as Foresight, Engagement and Integration [1,16,17] where foresight involves scenario planning, engagement involves the development of adaptation strategies and integration with policy involves monitoring and action. While meriting further elaboration, we propose that the concept of anticipatory governance could be applied to the development of an implementing agreement on access and benefit-sharing not simply in terms of mitigating environmental risk but also as a broader framework for realising the economic potential of marine genetic resources from ABNJ in a way that supports and fosters marine scientific research, advances knowledge and understanding of the deep-sea and promotes economic growth. 
 
References
1 Guston DH (2014) Understanding 'anticipatory governance'. Social Studies Of Science 44: 218-242.
2 Quay R (2010) Anticipatory Governance. Journal of The American Planning Association 76: 496-511.
3 Department for Business, Innovation & Skills (2013) Strength and Opportunity 2013: The landscape of the medical biotechnology, industrial biotechnology and pharmaceutical sectors in the UK. London: HM Government.
4 OECD (2013) Marine Biotechnology: Enabling Solutions for Ocean Productivity and Sustainability. Paris: OECD Publishing.
5 Blunt JW, Copp BR, Keyzers RA, Munro MH, Prinsep MR (2013) Marine natural products. Natural Product Reports 30: 237-323.
6 Mayer AM, Rodríguez AD, Taglialatela-Scafati O, Fusetani N (2013) Marine pharmacology in 2009-2011: marine compounds with antibacterial, antidiabetic, antifungal, anti-inflammatory, antiprotozoal, antituberculosis, and antiviral activities; affecting the immune and nervous systems, and other miscellaneous mechanisms of action. Marine Drugs 11: 2510-2573.
7 Newman DJ, Cragg GM (2014) Marine-sourced anti-cancer and cancer pain control agents in clinical and late preclinical development. Marine Drugs 12: 255-278.
8 Leal MC, Puga J, Serodio J, Gomes NCM, Calado R (2012) Trends in the Discovery of New Marine Natural Products from Invertebrates over the Last Two Decades - Where and What Are We Bioprospecting? PLOS ONE 7(1): e30580. doi:10.1371/journal.pone.0030580 
9 Leal MC, Munro MH, Blunt JW, Puga J, Jesus B, et al. (2013) Biogeography and biodiscovery hotspots of macroalgal marine natural products. Natural Product Reports 30: 1380-1390.
10 Hu GP, Yuan J, Sun L, She ZG, Wu JH, et al. (2011) Statistical research on marine natural products based on data obtained between 1985 and 2008. Marine Drugs 9: 514-525.
11 Leary D, Vierros M, Hamon G, Arico S, Monagle C (2009) Marine genetic resources: A review of scientific and commercial interest. Marine Policy 33: 183-194.
12 Skropeta D (2008) Deep-sea natural products. Natural Product Reports 25: 1131-1166.
13 Martins A, Vieira H, Gaspar H, Santos S (2014) Marketed marine natural products in the pharmaceutical and cosmeceutical industries: tips for success. Marine Drugs 12: 1066-1101.
14 Arico S, Salpin C (2005) Bioprospecting of genetic resources in the deep seabed: scientific, legal and policy aspects. Yokohama: United Nations University, Institute of Advanced Studies.
15 Kim S-K, Dewapriya P (2013) Active Ingredients from Marine Microorganisms for Modern Nutraceuticals. In, Marine Nutraceuticals: Prospects and Perspectives, edited by Kim Se-Kwon. New York: CRC Press.
16 Fuerth LS (2009) Foresight and anticipatory governance. Foresight 11: 14-32.
17 Fuerth LS, Faber EMH (2013) Anticipatory Governance: Winning the Future. Futurist 47: 42-4+
