---
title: "Annex 2"
author: "Paul Oldham"
date: "1 June 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Annex 2
In this annex we provide a series of reference examples from the data on origins and sources. 
Named Locations in Patent Data
The East Pacific Rise
Sample Isolated from a Named Location - East Pacific Rise
Example 1. “The native DNA polymerase is purified from a strain of E. coli that carries a modified DNA Polymerase gene (see Southworth et al., (1996) Proc. Natl. Acad. Sci. USA 93:5281-5285) from the extremely thermophilic marine archaea Thermococcus species, strain 9°N-7. The archaea is isolated from a submarine thermal vent, at a depth of 2,500 meters, north of the equator at the East Pacific Rise. The native DNA polymerase has proofreading exonuclease activity.” (US20070048748A1)
Example 2. “Thermococcus 9N-2 is from the genus Thermococcus 9N-2 was isolated from diffuse vent fluid in the East Pacific Rise. It is a strict anaerobe that grows optimally at 87°C. 100561 Thermotoga maritime MSB8 and MSB8 (Clone # 6GP2 and 6GB4) from the genus Thermotogo, isolated from Vulcano, Italy. MSB8 grows optimally at 85°C, pH 6.5 in a high salt medium (marine) containing starch and yeast extract as substrates and N2 in gas phase.” (WO2003072717A2)
Example 3. “20 entire full-grown and sexually mature Pompeii worms were collected on the East Pacific Rise, at 3,000 meters deep. These adult worms were crushed, and the homogeneous resulting mixture was acidified to pH 3 by addition of HCl 1M. Then the solution was centrifuged at 10,000g during 30 minutes. Proteins were thus concentrated in the centrifugation pellet and eliminated.” (WO2011076605A1)
Juan de Fuca Ridge
Sample Isolated from a Named Location - Juan de Fuca Ridge
Example 4. “A Thermococcus species was cultured from submarine samples taken from the Juan de Fuca ridge. Genomic DNA was isolated and used to prepare a genomic DNA library in ZAP II 5 (Stratagene) using standard procedures. The lambda library was plated on XL1-Blue MRF' E. colt and screened for clones with DNA polymerase activity using a variation of the method described by Sagner et al., (Sagner, G., Ruger, R., and Kessler, C. (1991) Gene 97:119-123). Plaques containing active polymerase were cored and stored in SM buffer. Positive primary plaques were re-plated and re-assayed to allow purification of isolated clones. Secondary clones were excised according to the 10 instructions provided with the ZAP II system (Stratagene), and the DNA sequence of the insert determined (Figure 1).” (WO2003054139A2)
Example 5. “A thermostable DNA polymerase gene for Tba DNA polymerase was isolated and cloned from Thermococcus barossii, a thermophilic organism obtained from deep vent flange, Endeavor Segment, Juan de Fuca Ridge, off the coast of Washington State in the U.S.A. (Duffaud GD, Syst Appl Microbiol. 21(l): 40-49 (1998)). Characterization of the purified Tba DNA polymerase showed that it possesses an active proofreading function in addition to its DNA-dependent DNA polymerase activity.” (WO2009085333A1)
East Manus Basin
Sample Isolated from a Named Location - East Manus Basin
Example 6. “In a first aspect, the present invention provides hydrogenases which are produced by the novel hyperthermophilic strain Thermococcus onnurineus NA1 (accession number: KCTC 10859BP) that produces hydrogen in anaerobic conditions. The strain was isolated from a deep-sea hydrothermal vent area at the PACMANUS field in the East Manus Basin. The isolated strain was deposited in the Korean Collection for Type Cultures (KCTC) at the Korean Research Institute of Bioscience and Biotechnology (KRIBB) on October 7, 2005 and assigned accession number KCTC 10859BP on October 20, 2005. The characteristics and culture methods of the strain are described in Korean Patent Application No. 1020070127255KR10-2007-0127255 on which the present invention is based.” (EP2333054A2)
Example 7. “PCR, which uses the thermostable DNA polymerase, is one of the most important contributions to protein and genetic research and is currently used in a broad array of biological applications. More than 50 DNA polymerase genes have been cloned from various organisms, including thermophiles and archaeas. Recently, family B DNA polymerases from hyperthermoph ilic archaea, Pyrococcus and Thermococcus, have been widely used since they have higher fidelity in PCR based on their proof reading activity than Taq polymerase commonly used. However, the improvement of the high fidelity enzyme has been on demand due to lower DNA elongation ability. The present inventors isolated a new hyperthermophilic strain from a deep-sea hydrothermal vent area at the PACMANUS field. It was identified as a member of Thermococcus based on 16S rDNA sequence analysis, and the whole genome sequencing is currently in process to search for many extremely thermostable enzymes. The analysis of the genome information displayed that the strain possessed a family B type DNA polymerase. The present inventors cloned the gene corresponding to the DNA polymerase and this was then expressed in E. coil. In addition, the recombinant enzyme was purified and its enzymatic characteristics were examined. 
Accordingly, the present inventors have isolated and prepared DNA polymerase from hyperthermophilic archaebacterium Thermococcus sp. NAI, thereby completing the present invention.” (WO2007043769A1)
“Cloning and primary sequence analysis of TNAI p01 gene Thermococcus sp. NAI was isolated from deep-sea hydrothermal vent area at the PACMANUS field (3° 14' 5, and 151° 42' E) in East Manus Basin. An YPS medium [see reference 10] was used to culture Thermococcus sp. NAI for DNA manipulation, and the culture and maintenance of Thermococcus sp. NAI were io conducted according to standard methods [see reference 11]. To prepare a Thermococcus sp. NAI seed culture, an YPS medium in a 25-mi serum bottle was inoculated with a single colony formed on a phytagel plate, and cultured at 90°C for 20 hours. The seed culture was used to inoculate 700 ml of an YPS medium in an anaerobic jar, and was cultured at 90°C for 20 hours.” (WO2007043769A1)
Example 8. “[Background Art] The present inventors isolated a new hyperthermophilic strain from a deep-sea hydrothermal vent area at the PACMANUS field. It was identified as a member of Thermococcus based on 16S rDNA sequence analysis, and the whole genome sequencing is currently in process to search for many extremely thermostable enzymes. The analysis of the genome information displayed that the strain possessed a family B type DNA polymerase. The present inventors cloned the gene corresponding to the DNA polymerase and expressed in E. coli. In addition, the recombinant enzyme was purified and its enzymatic characteristics were examined. Therefore, the present inventors applied for a patent on the DNA polymerase having high DNA elongation and high fidelity ability (Korean Patent Application No. 2005-0094644). But because of strong exonuclease activity and low processivity, high fidelity DNA polymerases need to improve in various applications of PCR.” (WO2008066350A1)
“Example 1… Cloning of TNAl HAM-I genes and expression of recombinant proteins Strains and culture conditions Thermococcus sp. NAl was isolated from a deep-sea hydrothermal vent area in the East Manus Basin. YPS medium was used to culture Thermococcus sp. NAl for DNA manipulation. Culture and strain maintenance were performed according to standard procedures. To prepare a seed culture of Thermococcus sp. NAl, YPS medium in a 25-ml serum bottle was inoculated with a single colony from a phytagel plate and cultured at 900C for 20 h. Seed cultures were used to inoculate 700 m l of YPS medium in an anaerobic jar and cultured at 90°C for 2O h . E . coli strain DH5± was used for plasmid propagation and nucleotide sequencing. E. coli strain BL21-CodonPlus (DE3) -RIL cells (Stratagene, LaJoIIa, CA) and the plasmid pET-24a( +) (Novagen, Madison, WI) were used for gene expression. E . coli strains were cultivated in Luria-Bertani medium with 50µg/ml kanamycin at 37°C.” (WO2008066350A1)
Sample Isolated from a Named Location /Acquired Through a Third Party – East Manus Basin
Example 9. “In a first aspect, the present invention provides hydrogenases which are produced by the novel hyperthermophilic strain Thermococcus onnurineus NA1 (accession number: KCTC 10859BP) that produces hydrogen in anaerobic conditions. The strain was isolated from a deep-sea hydrothermal vent area at the PACMANUS field in the East Manus Basin. The isolated strain was deposited in the Korean Collection for Type Cultures (KCTC) at the Korean Research Institute of Bioscience and Biotechnology (KRIBB) on Oct. 7, 2005 and assigned accession number KCTC 10859BP on Oct. 20, 2005. The characteristics and culture methods of the strain are described in Korean Patent Application No. 10-2007-0127255 on which the present invention is based.” (US20100311142A1)
Uranian Basin (Mediterranean) and Hawaii
Sample Isolated from Named Locations - Uranian Basin (Ionian Sea) and Pacific Ocean (Hawaii)
Example 10. “Characterization of Native NiFe-hydrogenase from Marine bacterium Alteromonas macleodii Alteromonas macleodii (strain deep ecotype, "AmDE") is one of 135 marine microbes sequenced at Venter Institute. It is a gram-negative, heterotrophic marine bacterium that grows under aerobic conditions. The Alteromonas macleodii strain deep ecotype (AmDE) was isolated from deep water (3500 meters) in Uranian Basin (Crete, Ionian), has an optimal growth temperature of 20C, and contains only one hydrogenase in its genome. (In contrast, Alteromonas macleodii strain 107 (Am107) from the ATCC was isolated from superficial water in the Pacific Ocean (Oahu, Hawaii), has an optimal growth temperature of 20C, and contains no hydrogenase.) The hydrogenase is illustrated in Figure 8.” (WO2008143630A2)
 
Kolbeinsey Ridge
Sample Isolated from a Named Location - Kolbeinsey Ridge
Example 11. “Methanococcus igneus KOL5 is a Euryarchaeoca isolated from Kolbeinsey Ridge in the north of Iceland. It grows optimally at 85C and pH 7.0 in a high-salt marine medium with H2/CO2 in a gas phase. Aquifex pyrophilus KOL 5A is a marine bacteria isolated from the Kolbeinsey Ridge in the north of Iceland. It is a gram-negative, rod-shaped, strictly chemolithoautotrophic, knall gas bacterium, and a denitrifier. It grows optimally at 85C in high-salt marine medium at pH 6.8 with 02 as a substrate and H,/CO, + 0. 5% 0, in gas phase.-Thex-mococcus alcaliphilus AEDII12R.A is from the genus Thermococcus. AEDII12RA grows optimally at 85C, pH 9.5 in a high salt medium (marine) containing polysulfides and yeast extract as substrates and N2 in gas phase.” (WO1997048416A1)
North Fiji Basin
Sample Isolated from a Named Location/Acquired Through a Third Party - North Fiji Basin
Example 12. “The strains Pyrococcus furiosus (DSM 5262) and Thermococcus litoralis (DSM 5474) were obtained from the collection of the German Collection of Microorganisms (DSM) Braunschweig--Stocheim, Germany. The strains Pyrococcus sp. G 23 and G 5 were isolated from vents of deep hydrothermal springs discovered in the Starmer Franco-Japanese campaign occurring in 1989 at 2000 m depth in the North-Fiji basin.” (US6673585B1)
Example 13. “La souche Thermococcus fumicolans obtenue aupres du laboratoire de Microbiologie Marine (de CC Barbier (IFREMER-DRV-VP-CMM) Ã  Brest, France. Cette souche, Thermococcus fumicolans  obtenue par purification Ã  partir de fragments de chemines hydrothermales receuillies dans le bassin nord-Fidgien lors de la campagne franco-japonaise STARMER effectue en 1989-2000 metres de profondeur.” (WO1998049274A1)
Multiple Locations 
(Mid-Atlantic Ridge, Kolbeinsey Ridge, Juan De Fuca Ridge, Guaymas Basin)
Samples from Multiple Named Locations/Acquired Through a Third Party 
Example 14. “The polynucleotides of this invention were originally recovered from genomic gene libraries derived from the following organisms: Pyrodictium TAG I I is a thermophilic sulfur archaea which was isolated in the Middle Atlantic Ridge. It grows optimally at 103"C (T,,,, = 110'C) at pH 6.5. Archaeoglobus venificus SNP6 was isolated in the Middle Atlantic Ridge and grows optimally at 75'C (Tmax 92*C) at pH 6.9. Aquifex pyrophilus KOI 5a was isolated at Kolbeinsey Ridge, North of Iceland. This marine organism is a gram-negative, rod-shaped, strictly chemolithoautrophic, knall gas bacterium. It grows optimally at 85'C (Tmax = 95'Q at pH 6.8’ ‘Thermococcus CL-2 was isolated in the North Cleft Segment of the Juan de Fuca Ridge from a severed alvinellid worm residing on a "black smoker" sulfide structure. This marine archaea forms pleomorphic cocci, and grows optimally at 88C.” (WO1997030160A1)
Example 15. “The polynucleotides of this invention were originally recovered from genomic gene libraries derived from the following organisms: Thermococcus GUSL5 is an Euryarchaeota isolated from the Guaymas Basin in Mexico. It grows optimally at 850C and pH 6.0 in a high-salt marine medium containing 1% elemental sulfur, 0.4% yeast extract, and 0.5% peptone as substrates with N2 in gas phase… 
Thermococcus CL-2 is an Euryarchaeota isolated from the North Cleft Segment in the Juan de Fuca Ridge. It grows optimally at 88C in a salt medium with an argon atmosphere…
Methanococcus igneus KOL5 is a Euryarchaeoca isolated from Kolbeinsey Ridge in the north of Iceland. I t grows optimally at 85C and pH 7.0 in a high-salt marine medium with H2/CO2 in a gas phase. Aquifex pyrophilus KOL 5A is a marine bacteria isolated from the Kolbeinsey Ridge in the north of Iceland. It is a gram-negative, rod-shaped, strictly chemolithoautotrophic, knall gas bacterium, and a denitrifier. It grows optimally at 85C in high-salt marine medium at pH 6.8 with 02 as a substrate and H,/CO, + 0. 5% 0, in gas phase.-Thex-mococcus alcaliphilus AEDII12R.A is from the genus Thermococcus. AEDII12RA grows optimally at 85C, pH 9.5 in a high salt medium (marine) containing polysulfides and yeast extract as substrates and N2 in gas phase…
Many of these organisms grow at temperatures up to about 103C and are unable to grow below 70C. These anaerobes are isolated from extreme environments. For example, Thermococcus CL-2 was isolated from a worm residing on a "black smoker" sulfite structure.” (WO1997048416A1).
 
Broad Geographical Areas
Broad Geographical Areas - Seas Around Japan
Example 16. “In the present specification, it is sufficient that the "krill" be an arthropod belonging to the phylum Arthropoda, subphylum Crustacea, class Malacostraca and includes arthropods belonging to the phylum Arthropoda, subphylum Crustacea, class Malacostraca, order Eucarida, family Euphausiacea such as, for example, Euphausia superba, and arthropods belonging to the phylum Arthropoda, subphylum Crustacea, class Malacostraca, order Euphausiacea, family Euphausiidae such as, for example, Mysidacea caught in the seas around Japan, and the like. However, from the perspective of stability of catch volume and uniformity of the lipid component, Antarctic krill are particularly preferable. In the present specification, "lipid of krill origin" refers to a lipid obtained from the krill described above.” (WO2012103692A1)
Broad Geographical Areas - Norwegian Waters and Southern Ocean
Example 17. “Table 1. Typical chemical composition of three different marine oils: (A) Copepod oil from Calanus finmarchicus caught in Norwegian waters, (B) cod liver oil from Atlantic cod Gadus morhua, and (C) krill oil from Euphausia superba caught in the Southern ocean, given in mg/g oil.” (WO2010143977A1)
Example 18. “Table 1. Typical chemical composition of three different marine oils: (A) Copepod oil from Calanus finmarchicus caught in Norwegian waters, (B) cod liver oil from Atlantic cod Gadus morhua, and (C) krill oil from Euphausia superba caught in the Southern ocean, given in mg/g oil.” (WO2010077152A1)
Broad Geographical Areas - Norwegian Waters and Weddell Sea
Example 19. “Table 2. Fatty acid composition of three different marine oils: (A) Copepod oil from Calanus finmarchicus caught in Norwegian waters, (B) cod liver oil from Atlantic cod Gadus morhua, and (C) krill oil from Euphausia superba caught in the Weddell Sea, given in mg/g oil.” (WO2010077152A1)
Broad Geographical Areas - Antarctica
Example 20. “Antarctic krill (Euphausia superba) was captured and brought on board alive, before it was processed into krill meal, an oil (asta oil), and stickwater. During the krill meal processing a neutral oil (asta oil) is recovered.” (WO2010136900A2)
 
Broad Geographical Area - Arctic Marine Sediments and Indian Ocean
Example 21. “Colwellia psychrerythraea is a non-pathogenic, obligate psychrophile and Gram-negative bacteria. C. psychrerythraea is a member of the proteobacteria phylum, class gammaproteobacteria. This bacterium is rod-shaped, red in pigment, possesses flagella and can be found in cold marine environments such as the Arctic and Antarctic sea ice. Strain 34H, in particular, was isolated from Arctic marine sediments. Strain 34H of C. psychrerythraea has a growth temperature range of from’1° C. to 10° C. Optimal growth appears at 8° C., with maximum cell yield occurring at the subzero temperature of ’1° C. Cells are able to survive in temperatures as low as ’10° C. Growth can occur under deep sea pressure as well.” (US20100184156A1) 
Example 22. “Four new lamellarins: E-H were isolated and characterized from the marine ascidian Didemnum chartaceum obtained from the Indian Ocean. The structure of lamellarin E was determined by an X-Ray crystallographic study.” (US20060287529A1) 
Broad Geographical Areas - Mediterranean Sea
Example 23. “Example 1 A) Animals (Sepia officinalis) were caught in the Mediterranean sea for subsequent isolation of filled ink sack and parts of the organs being arranged closely to the ink sack. The ink sacks were isolated after opening the abdomen with a scalpel. The whole isolated ink sacks were then pressed mechanically and the natural ink sack liquid was collected into a recipient at room temperature. Parts of the accessory nidamental gland, the nidamental gland and the overy including gages were also derived from the above mentioned animals, homogenized and mixed with ink sack liquid in a weight ration of 30:70. Afterwards, this mixture was frozen and stored for 6 days for later processing. The unfrozen, undiluted mixture was then used for subsequent treatment.” (WO2008000454A2)
Specific Collection Locations
This data refers to cases where an applicant specifies that they collected the sample. 
Specific Collection Locations - Collected on beaches of Hawaii and Australia
Example 24. “Carybdea alata. Freshly beached, post-spawning Alatina moseri were collected in the early-morning hours along specific leeward Oahu (Hawaii) beaches during synchronized spawning cycles, occurring 8-10 days after each full moon. Tentacles were excised beachside and placed immediately into chilled 1 M citrate at approximately 1 :4 (v:v) in 50-mL tubes and agitated at 4°C for up to 8 weeks to recover all tentacular cnidae through a process of hypertonic mesogleal tissue contraction and intact cnidae sloughing. Contents were sieved (using 0.5-mm plankton sieves) to recover undischarged cnidae from the cnidae-free tentacles… 
Chironex fleckeri were collected in North Queensland Australia. Tentacles were excised beachside and frozen at -80°C. Aliquots of frozen tentacles were resuspended in 1 M citrate at approximately 1 :20 (v:v) in 50-mL tubes and agitated at 4°C for up to 2 weeks to recover all tentacular cnidae through a process of hypertonic mesogleal tissue contraction and intact cnidae sloughing. Contents were sieved (using 0.5-mm plankton sieves) to recover undischarged cnidae from the cnidae-free tentacles.” (WO2011038157A2)
Specific Collection Location - Weddell Sea
Example 25. “Aplidium cyaneum was collected by bottom trawling in Weddell Sea (Longitude: -10.533333, Latitude: -71.933333) at a depth ranging between 220 and 300 m. Two samples of the specimen were deposited in the Department of Environmental Sciences (Marine Biology Unit) of the University of Alicante (Spain). Their reference codes are ASC.ANT.EQ.433-1 and ASC.ANT.EQ. 1097- 1.” (WO2007054748A1)
Specific Collection Location - Georges Bank
Example 26. “Wild Atlantic cod were obtained from three sites off North America in late 2006 for ambient spawning in 2007. Broodstock were caught off Georges Bank (Northwest Atlantic Fisheries Organization division 5Z) and Cape Sable, Nova Scotia (NAFO Division 4X). Cod broodstock were transported to the Department of Fisheries and Oceans, St. Andrews Biological Station, Canada (SABS). A third site was located off New Hampshire (NAFO division 5Y) and cod broodstock were transported to Great Bay Aquaculture (GBA), New Hampshire, United States. All broodstock were maintained in tanks on a mixed ration of Atlantic mackerel (Scomber scombrus) and northern shortfin squid (///ex illecebrosus) with vitamin and mineral supplement twice weekly. Prior to spawning, broodstock were tagged with Passive Integrated Transponders (PIT, Sokymat, Switzerland) and fin clip tissue was collected.” (WO2010115275A1)
Specific Collection Location - Arcachon Bay, French Atlantic Coast
Example 27. “Corynactis viridis specimens were collected off the French Atlantic coast Arcachon Bay, France). Whole animals were frozen for total RNA extraction. Total RNA was extracted using RNAbIe buffer (Eurobio).” (WO2008085502A2)
 
Specific Collection Location - Gulf Coast of Florida 
Example 28. “Lemon sharks (Negaprion brevirostris) were caught off the Gulf Coast of Florida using hook and line. Epigonal tissue was obtained from fresh specimens and conditioned media were prepared as in Example 1. The conditioned media showed anti-proliferative activity on all tumor cell lines tested (A375.S2 and WEHI 164) and the effects of growth inhibition on dose are shown in FIGS. 6 and 7. Growth inhibition of WEHI 164 cells of >90% was achieved using a dose of approximately 3 mg/mL.” (US20050220893A1)
Specific Collection Location - Chesterfield Island, New Caledonia
Example 29. “Example 1: Material and Methods Materials Specimens of Conus consors were collected in Chesterfield Island (New Caledonia) and immediately frozen at 80°C. The venom was obtained from freshly dissected venom duct apparatus, and extracted with 0.08% trifluoroacetic acid (TFA) in water. Extracts obtained from several venom ducts were centrifuged to remove insoluble particles. Supernatants from all extractions were combined, lyophilised, weighed, and stored at - 80C until required for use.” (WO2007054785A1)
Specific Collection Location - Palmer Station (Antarctica)
Example 30. “"Palmerolide," as used herein, refers to a multi-membered macrocyclic polyketide bearing carbonate and amide functionality. In one embodiment, the Palmerolide is isolated from the tunicate Synoicum adareanum; collected from the vicinity of Palmer Station on the Antarctic Peninsula.” (WO2005079471A2)
Specific Collection Location / Acquired Through a Third Party – Florida, Panama and Commercial Source
Example 31. “Table 1: Comparison of Characteristics of Nicks Pdl and Dstl Mick Pdl Dstl Excitation Maximum: 492 nm 482 nm 438 nm Emission Maximum: 502 nm 494 nm 482 nm Nucleotides: 681 666 681 Amino Acids: 227 222 227 Materials and Methods Species collection and animal husbandry. Single, bright green colonies of Montastraea cavernosa and Montastraea faveolata colonies were collected from reefs in the South Florida area. A single branch from a large colony of Pocillopora damicornis was collected from the Pacific coast of Panama. Colony of Discosoma striata was purchased at a local aquarium store. All corals were maintained in flow through aquariums using filtered sea water at the Rosenstiel School of Marine and Atmospheric Sciences (University of Miami) until tissue processing could occur.” (WO2004094597A2)
Commercial Sources
Acquired Through a Third Party - Commercial Source
Example 32. “EXAMPLE 1: Isolation of Eleutherobin, nucleic acids and protein from cultured Erythropodium caribaeorum D0128] Approximately 2 kg of cultured Erythropodium caribaeorum is obtained from a commercial source, such as Ocean Dreams Inc. in Tampa, Florida. This is shipped in chilled seawater to retain the coral viability. This sample is divided and used for three purposes: 1) to verify the presence of eleutherobin within the sample, 2) to obtain genomic DNA and mRNA to be used in hybridization and PCR-based identification of terpene syntheses, and 3) to obtain cell lysates to be used in the functionally-based covalent modification of diterpene syntheses.” (WO2005057176A2)
Acquired Through a Third Party - Branded Commercial Product
Example 33. “3. Thermostable (useful for PCR assays)-e.g., Pyrococcus species Curious, species GB 5 D, species strain KODI, woesii, abysii, horikoshii), Thermococcus species (litoralis, species 9° North-7, species JDF-3, gorgonarius), Pyrodictium occultum, and Archaeoglobus fulgidus. It is estimated that suitable archaea would exhibit maximal growth temperatures of >80-85°C or optimal growth temperatures of >70-80°C. Appropriate PCR enzymes from the archaeal pot a DNA polymerase group are commercially available, including KOD (Toyobo), Pfx (Life 10 Technologies, Inc.), Vent (New England BioLabs), Deep Vent (New England BioLabs), and Tgo (Roche). Additional archaea related to those listed above are described in the following references: Archaea: A Laboratory Manua (Robb, F.T. and Place, A.R., eds.), Cold Spring Harbor Laboratory Press, Cold Spring Harbor, NY, 1995 and Thermophilic Bacteria (Kristjansson, 15 J.K., ed.) CRC Press, Inc., Boca Raton, Florida, 1992.” (WO2003052116A2)
Unspecified Location with Habitat Description:
Unspecified Location Habitat Description - High temperature environment
Example 34. “Cannulae nanotubules are characteristically formed by Pyrodictium abyssi, a hyperthermophilic microorganism discovered in a high temperature environment (>100 °C). In its natural environment and in cell culture, Pyrodictiun abyssi are linked together by a meshwork of these nanotubular fibers that both connect and entrap the cells.” (WO2005094543A2)
 
Unspecified Location Habitat Description - Hydrothermal Vents
Example 35. “The proof-reading DNA polymerases currently available commercially for PCR are derived from species within either the Pyrococcus genus or the Thermococcus genus of hyperthermophilic euryarchaeota. Archaea are a third domain of living organisms, distinct from Bacteria and Eucarya. These organisms have been isolated predominantly from deep-sea hydrothermal vents ("black smokers") and typically have optimal growth temperatures around 85-99C. Examples of key species from which proof-reading DNA polymerases for use in PCR have been isolated include Thermococcus barossii, Thermococcus litoralis, Thermococcus gorgonarius, Thermococcus paciÃŽÂ² cus, Thermococcus zilligii, Thermococcus 9N7, Thermococcus fumicolans, Thermococcus aggregans (TY), Thermococcus peptonophilus, Pyrococcus furiosus, Pyrococcus sp. and Thermococcus KOD….
Palaeococcus ferrophilus is a barophilic, hyperthermophilic archaeon isolated from a deep-sea hydrothermal vent chimney, and has a reported temperature range for growth of 60-880C and an optimum growth temperature of 83°C (see Takai et al., 2000, Int. J. Syst. Evol. Microbiol. 50: 489-500). This organism was reported to be the first member of the Palaeococcus genus of hyperthermophilic euryarchaeota, and to date there are no known published reports of the identification and characterisation of a DNA polymerase from this genus. Genomic DNA (gDNA) from P. ferrophilus has been isolated by the inventors, who used a sophisticated gene walking technique to clone a DNA polymerase, considered to be a DNA polymerase II encoded by a DNA polymerase II (polB) gene.” (WO2009112867A1)
Example 36. “An exemplary purified enzyme is a polymerase derived from an organism referred herein as "Pyrolobus fumaria," a hyperthermophile that grows in the walls of hydrothermal vents through which superheated, mineral-rich fluids erupt. Pyrolobus fumaria reproduces best in an environment of about 105°C and can multiply in temperatures of up to I 113°C, but stops growing at temperatures below 90°C. This exemplary enzyme (sequence shown in Figure 1 B) may be used to polymerize DNA where desired. The polymerase enzyme of the present invention has a very high thermos/ability and processivity. The Pyrolobus fumaria polymerase remains robustly active even after four or more hours at temperatures as high as 95°C to 113°C. Therefore it is particularly useful and reliable for PCR amplification of template molecules greater than 20 kb in length and/or having a GO! content of greater than about 90%, templates which typically require longer amplification times and higher temperatures.” (WO2003023029A1)
Example 37. “The 16S rDNA was used to define the association of strain N4-7 to other cultured organisms. Interpretatively, alone and after synthesis of all other tests, we feel confident that a 92% identity value, as in the case of S. maltophilia, is sufficiently divergent to exclude any relatedness at a genus level. However, this argument is not true for a 98% identity value found to the three hydrothermal vent eubacterium. In some instances, a high similarity value such as this is appropriate for species level grouping when comparing organisms which share phenotypic qualities, however, given the uniqueness of habitat in which the vent eubacterium DNA was isolated, it seems unlikely that strain N4-7 fits into this taxa. 
The value of 16S rDNA sequence is only as good as the quality of sequence entered in the database. Often, sequences are incomplete or inaccurate, clearly skewing the alignments. To diminish error introduced from the database sources, we have confirmed regions in S. maltophilia by our own sequencing and also eliminated bases within the constant, non-variable domains of the 16S rDNA that were incomplete for all isolates tested by filtering with the Clustal method.” (WO1999055833A2)
Example 38. “As has been noted, environmental conditions such as temperature may affect the chemistry and properties of extracellular precipitates produced in accordance with the present invention. Other environmental conditions may be used to control or alter the products that are formed as well. For example, pressure may also be a useful parameter in controlling the type of nanophase material that is produced in accordance with the present invention. Barophilic manganese-oxidizing bacteria have been isolated from ferromanganese nodules from the deep sea and around hydrothermal vents. Such microbes possess unusual means for interacting with inorganic ions and may be exploited in the production of novel nanophase materials with unusual properties.” (US20050013759A1)
Unspecified Location Habitat Description – Deep Hydrothermal Ecosystems/Habitats
Example 39. “The invention relates to the use of a polysaccharide which is excreted by the Vibrio diabolicus species for the re-generation and protection of the non-mineralised connective tissue of the periodontium…
The present invention relates to the regeneration of the non-mineralized connective tissue of the periodontium. Exopolysaccharide (EPS)-producing bacteria have been isolated from microorganisms originating from deep hydrothermal ecosystems. HE800 is an EPS produced by the Vibrio diabolicus strain. Its weight-average molecular mass is approximately 800 000 g/mol in the native state. It is characterized by an original linear repeating oside sequence consisting of 4 oside residues.” (US20090028924A1)
Example 40. “The invention relates to certain low-molecular weight sulphated polysaccharide derivatives of marine native exopolysaccharides (EPSs) excreted by mesophilic marine bacteria from a deep hydrothermal environment, wherein said derivatives can be obtained by means of a method which comprises a step of free radical depolymerisation of said native EPSs followed by a step of sulphating the resulting depolymerised derivatives. The present invention further relates to the use of said low-molecular weight sulphated polysaccharide derivatives as a wound-healing agent, particularly for preparing pharmaceutical compositions suitable for treating or preventing diseases of the connective tissues and particularly skin and gum tissues. The figure demonstrates how polysaccharide derivative GY 785 DRS according to the invention can stimulate fibroblast proliferation in latticed or reconstructed connective tissues at a concentration of 10 Î¼g(m)g/ml.” (US20080131472A1)
Unspecified Location Habitat Description - Depth of 300–600 m 
Example 41. “Hoki (Macruronus novaezealandiae) is New Zealand's most important commercial fish species. It lives mainly in the middle water depths and is taken by mid-water trawling, usually at depths of around 300-600 metres. Most hoki are between 60-100 cm long. Other names include blue hake, blue grenadier, whiting (incorrectly) and whiptail.
The oil extracted from the livers of hoki has been found by the applicant to exhibit several potent biological modulatory activities. It shows strong anti-inflammatory activity. It also suppresses superoxide production by activated neutrophils. Although there is increased inhibitory response with increasing doses of hoki liver oil, this increase does not follow a linear pattern. Additionally, when the oil is diluted 10-fold and re-assayed the inhibition remains but again the linearity of response is not strong.” (WO2006004438A1)
Unspecified Location habitat Description – Chemoautotrophs - List of Habitats
Example 42. “The different chemoautotrophs that can be used in the present invention may be native to a range environments including but not limited to hydrothermal vents, geothermal vents, hot springs, cold seeps, underground aquifers, salt lakes, saline formations, mines, acid mine drainage, mine tailings, oil wells, refinery wastewater, coal seams, the deep sub-surface, waste water and sewage treatment plants, geothermal power plants, sulfatara fields, soils. They may or may not be extremophiles including but not limited to thermophiles, hyperthermophiles, acidophiles, halophiles, and psychrophiles… 
A method according to any preceding claim, wherein the obligate and/or facultative chemoautotrophic microorganisms include one or more of the following: Acetoanaerobium sp.; Acetobacteriumsp.; Acetogenium sp.; Achromobacter sp.; Acidianus sp.; Acinetobacter sp.; Actinomadura sp.; Aeromonas sp.; Alcaligenes sp.; Alcaliqenes sp.; Arcobacter sp.; Aureobacterium sp.; Bacillus sp.; Beggiatoa sp.; Butyribacterium sp.; Carboxydothermus sp.; Clostridium sp.; Comamonas sp.; Dehalobacter sp.; Dehalococcoide sp.; Dehalospirillum sp.; Desulfobacterium sp.; Desulfomonile sp.; Desulfotomaculum sp.; Desulfovibrio sp.; Desulfurosarcina sp.; Ectothiorhodospira sp.; Enterobacter sp.; Eubacterium sp.; Ferroplasma sp.; Halothibacillus sp.; Hydrogenobacter sp.; Hydrogenomonas sp.; Leptospirillum sp.; Metallosphaera sp.; Methanobacterium sp.; Methanobrevibacter sp.; Methanococcus sp.; Methanosarcina sp.; Micrococcus sp.; Nitrobacter sp.; Nitrosococcus sp.;  Nitrosolobus sp.; Nitrosomonas sp.; Nitrosospira sp. ; Nitrosovibrio sp.; Nitrospina sp.; Oleomonas sp.; Paracoccus sp.; Peptostreptococcus sp.; Planctomycetes sp.; Pseudomonas sp.; Ralstonia sp.; Rhodobacter sp.; Rhodococcus sp.; Rhodocyclus sp.; Rhodomicrobium sp.; Rhodopseudomonas sp.; Rhodospirillum sp.; Shewanella sp.; Streptomyces sp.; Sulfobacillus sp.; Sulfolobus sp.; Thiobacillus sp.; Thiomicrospira sp.; Thioploca sp.; Thiosphaera sp.; Thiothrix sp.; sulfur-oxidizers; hydrogen- oxidizers; iron-oxidizers; acetogens; and methanogens; consortiums of microorganisms that include chemoautotrophs; chemoautotrophs native to at least one of hydrothermal vents, geothermal vents, hot springs, cold seeps, underground aquifers, salt lakes, saline formations, mines, acid mine drainage, mine tailings, oil wells, refinery wastewater. Coal seams, deep sub-surface; waste water and sewage treatment plants; geothermal power plants, sulfatara fields, and soils; and extremophiles selected from one or more of thermophiles, hyperthermophiles, acidophiles, halophiles, and psychrophiles.” (WO2011056183A1)
